import { TerminalThemeId, BytezinhoSkinId, KeySoundThemeId, CosmeticCurrency } from '../types/cosmetics';

export interface TerminalThemeConfig {
  id: TerminalThemeId;
  name: string;
  subtitle: string;
  description: string;
  price: number;
  currency?: CosmeticCurrency;
  effectType:
    | 'matrix_rain'
    | 'dracula_mist'
    | 'amber_crt'
    | 'cyber_glitch'
    | 'monokai_code'
    | 'synthwave_grid'
    | 'solarized_waves'
    | 'nordic_snow'
    | 'magma_embers'
    | 'golden_sparkles'
    | 'mint_scanlines'
    | 'sith_lightning'
    | 'saiyan_aura'
    | 'nether_flame'
    | 'spider_web';
  previewColors: {
    bg: string;
    card: string;
    accent: string;
    text: string;
  };
  classes: {
    appBg: string;
    headerBg: string;
    cardBg: string;
    cardBorder: string;
    textPrimary: string;
    textSecondary: string;
    textAccent: string;
    accentBg: string;
    accentBorder: string;
    badgeBg: string;
    arenaBorder: string;
    glow: string;
    glowEffect: string;
    charDone: string;
    charCurrent: string;
    cursor: string;
  };
}

export const TERMINAL_THEMES: Record<TerminalThemeId, TerminalThemeConfig> = {
  matrix: {
    id: 'matrix',
    name: 'Matrix Verde',
    subtitle: 'Terminal Clássico',
    description: 'Estilo clássico dos terminais de fósforo verde com caracteres em chuva digital.',
    price: 0,
    effectType: 'matrix_rain',
    previewColors: {
      bg: '#0a0d0a',
      card: '#0e140f',
      accent: '#10b981',
      text: '#34d399',
    },
    classes: {
      appBg: 'bg-[#0a0d0a]',
      headerBg: 'bg-[#0e140f]/95 border-[#1a2e1d]',
      cardBg: 'bg-[#0f1711]',
      cardBorder: 'border-[#1b3320]',
      textPrimary: 'text-zinc-100',
      textSecondary: 'text-emerald-400/80',
      textAccent: 'text-emerald-400',
      accentBg: 'bg-emerald-500/15',
      accentBorder: 'border-emerald-500/40',
      badgeBg: 'bg-emerald-950/60 text-emerald-300 border-emerald-500/40',
      arenaBorder: 'border-emerald-500/40 focus-within:border-emerald-400 focus-within:shadow-[0_0_25px_rgba(16,185,129,0.25)]',
      glow: 'shadow-[0_0_20px_rgba(16,185,129,0.2)]',
      glowEffect: 'shadow-[0_12px_36px_rgba(16,185,129,0.15)]',
      charDone: 'text-emerald-400',
      charCurrent: 'text-emerald-300 bg-emerald-950/60 ring-2 ring-emerald-400/80 shadow-[0_0_15px_rgba(16,185,129,0.4)]',
      cursor: 'bg-emerald-400 shadow-[0_0_8px_#10b981]',
    },
  },
  dracula: {
    id: 'dracula',
    name: 'Dracula Vamp',
    subtitle: 'Dark Violeta & Ciano',
    description: 'Paleta dark elegante com violeta escuro, fúcsia e névoa etérea pulsante.',
    price: 3,
    effectType: 'dracula_mist',
    previewColors: {
      bg: '#0d0b14',
      card: '#161224',
      accent: '#bd93f9',
      text: '#8be9fd',
    },
    classes: {
      appBg: 'bg-[#0d0b14]',
      headerBg: 'bg-[#151124]/95 border-[#2b214a]',
      cardBg: 'bg-[#161224]',
      cardBorder: 'border-[#2d224e]',
      textPrimary: 'text-zinc-100',
      textSecondary: 'text-purple-300/80',
      textAccent: 'text-purple-400',
      accentBg: 'bg-purple-500/15',
      accentBorder: 'border-purple-500/40',
      badgeBg: 'bg-purple-950/60 text-purple-300 border-purple-500/40',
      arenaBorder: 'border-purple-500/40 focus-within:border-purple-400 focus-within:shadow-[0_0_25px_rgba(168,85,247,0.25)]',
      glow: 'shadow-[0_0_20px_rgba(168,85,247,0.2)]',
      glowEffect: 'shadow-[0_12px_36px_rgba(168,85,247,0.18)]',
      charDone: 'text-purple-400',
      charCurrent: 'text-cyan-300 bg-purple-950/70 ring-2 ring-cyan-400/80 shadow-[0_0_15px_rgba(139,233,253,0.4)]',
      cursor: 'bg-cyan-400 shadow-[0_0_8px_#8be9fd]',
    },
  },
  amber: {
    id: 'amber',
    name: 'Fósforo Âmbar',
    subtitle: 'CRT Vintage 1982',
    description: 'Monitores mono-âmbar com feixe de varredura CRT e calor nostálgico dos primeiros PCs.',
    price: 2,
    effectType: 'amber_crt',
    previewColors: {
      bg: '#0f0c08',
      card: '#1c150c',
      accent: '#f59e0b',
      text: '#fbbf24',
    },
    classes: {
      appBg: 'bg-[#0f0c08]',
      headerBg: 'bg-[#1a130a]/95 border-[#382613]',
      cardBg: 'bg-[#1c150c]',
      cardBorder: 'border-[#3d2914]',
      textPrimary: 'text-zinc-100',
      textSecondary: 'text-amber-400/80',
      textAccent: 'text-amber-400',
      accentBg: 'bg-amber-500/15',
      accentBorder: 'border-amber-500/40',
      badgeBg: 'bg-amber-950/60 text-amber-300 border-amber-500/40',
      arenaBorder: 'border-amber-500/40 focus-within:border-amber-400 focus-within:shadow-[0_0_25px_rgba(245,158,11,0.25)]',
      glow: 'shadow-[0_0_20px_rgba(245,158,11,0.2)]',
      glowEffect: 'shadow-[0_12px_36px_rgba(245,158,11,0.2)]',
      charDone: 'text-amber-400',
      charCurrent: 'text-amber-200 bg-amber-950/70 ring-2 ring-amber-400/80 shadow-[0_0_15px_rgba(251,191,36,0.5)]',
      cursor: 'bg-amber-400 shadow-[0_0_8px_#fbbf24]',
    },
  },
  cyberpunk: {
    id: 'cyberpunk',
    name: 'Cyberpunk Neon',
    subtitle: 'High Tech, Night City',
    description: 'Amarelo cromo e azul ciano vibrante com feixes de circuitos eletrônicos pulsantes.',
    price: 4,
    effectType: 'cyber_glitch',
    previewColors: {
      bg: '#080c14',
      card: '#0c1524',
      accent: '#06b6d4',
      text: '#facc15',
    },
    classes: {
      appBg: 'bg-[#080c14]',
      headerBg: 'bg-[#0b1424]/95 border-[#162a4a]',
      cardBg: 'bg-[#0c1524]',
      cardBorder: 'border-[#182f54]',
      textPrimary: 'text-zinc-100',
      textSecondary: 'text-cyan-400/80',
      textAccent: 'text-cyan-400',
      accentBg: 'bg-cyan-500/15',
      accentBorder: 'border-cyan-500/40',
      badgeBg: 'bg-cyan-950/60 text-cyan-300 border-cyan-500/40',
      arenaBorder: 'border-cyan-500/40 focus-within:border-cyan-400 focus-within:shadow-[0_0_25px_rgba(6,182,212,0.25)]',
      glow: 'shadow-[0_0_20px_rgba(6,182,212,0.2)]',
      glowEffect: 'shadow-[0_12px_36px_rgba(6,182,212,0.25)]',
      charDone: 'text-cyan-400',
      charCurrent: 'text-yellow-300 bg-cyan-950/70 ring-2 ring-yellow-400/80 shadow-[0_0_15px_rgba(250,204,21,0.5)]',
      cursor: 'bg-yellow-400 shadow-[0_0_8px_#facc15]',
    },
  },
  monokai: {
    id: 'monokai',
    name: 'Monokai Pro',
    subtitle: 'IDE de Programação',
    description: 'Tema clássico de editores de código com tokens de programação flutuantes e sintaxe viva.',
    price: 3,
    effectType: 'monokai_code',
    previewColors: {
      bg: '#141512',
      card: '#1e1f1a',
      accent: '#a6e22e',
      text: '#f92672',
    },
    classes: {
      appBg: 'bg-[#141512]',
      headerBg: 'bg-[#1c1d17]/95 border-[#34362b]',
      cardBg: 'bg-[#1e1f1a]',
      cardBorder: 'border-[#383a2d]',
      textPrimary: 'text-zinc-100',
      textSecondary: 'text-lime-400/80',
      textAccent: 'text-lime-400',
      accentBg: 'bg-lime-500/15',
      accentBorder: 'border-lime-500/40',
      badgeBg: 'bg-lime-950/60 text-lime-300 border-lime-500/40',
      arenaBorder: 'border-lime-500/40 focus-within:border-lime-400 focus-within:shadow-[0_0_25px_rgba(163,230,53,0.25)]',
      glow: 'shadow-[0_0_20px_rgba(163,230,53,0.2)]',
      glowEffect: 'shadow-[0_12px_36px_rgba(163,230,53,0.18)]',
      charDone: 'text-lime-400',
      charCurrent: 'text-pink-300 bg-lime-950/60 ring-2 ring-pink-500/80 shadow-[0_0_15px_rgba(249,38,114,0.4)]',
      cursor: 'bg-pink-500 shadow-[0_0_8px_#f92672]',
    },
  },
  synthwave: {
    id: 'synthwave',
    name: 'Synthwave 84',
    subtitle: 'Outrun & Retrowave',
    description: 'Pôr-do-sol retrô futurista com grade de perspectiva ondulante em magenta e azul elétrico.',
    price: 4,
    effectType: 'synthwave_grid',
    previewColors: {
      bg: '#130a1e',
      card: '#1f1033',
      accent: '#f43f5e',
      text: '#38bdf8',
    },
    classes: {
      appBg: 'bg-[#130a1e]',
      headerBg: 'bg-[#1c0e2e]/95 border-[#421d66]',
      cardBg: 'bg-[#1f1033]',
      cardBorder: 'border-[#4a2273]',
      textPrimary: 'text-zinc-100',
      textSecondary: 'text-pink-400/80',
      textAccent: 'text-pink-400',
      accentBg: 'bg-pink-500/15',
      accentBorder: 'border-pink-500/40',
      badgeBg: 'bg-pink-950/60 text-pink-300 border-pink-500/40',
      arenaBorder: 'border-pink-500/40 focus-within:border-pink-400 focus-within:shadow-[0_0_25px_rgba(244,63,94,0.3)]',
      glow: 'shadow-[0_0_20px_rgba(244,63,94,0.25)]',
      glowEffect: 'shadow-[0_12px_36px_rgba(244,63,94,0.25)]',
      charDone: 'text-pink-400',
      charCurrent: 'text-cyan-300 bg-pink-950/70 ring-2 ring-cyan-400/80 shadow-[0_0_15px_rgba(56,189,248,0.5)]',
      cursor: 'bg-cyan-400 shadow-[0_0_8px_#38bdf8]',
    },
  },
  solarized_dark: {
    id: 'solarized_dark',
    name: 'Solarized Dark',
    subtitle: 'Harmonia Espectral',
    description: 'Oceano azul solar escuro com curvas harmônicas calmas e legibilidade científica suprema.',
    price: 3,
    effectType: 'solarized_waves',
    previewColors: {
      bg: '#001e26',
      card: '#073642',
      accent: '#2aa198',
      text: '#b58900',
    },
    classes: {
      appBg: 'bg-[#001e26]',
      headerBg: 'bg-[#042833]/95 border-[#0d4f61]',
      cardBg: 'bg-[#073642]',
      cardBorder: 'border-[#0e5264]',
      textPrimary: 'text-zinc-100',
      textSecondary: 'text-teal-300/80',
      textAccent: 'text-teal-300',
      accentBg: 'bg-teal-500/15',
      accentBorder: 'border-teal-500/40',
      badgeBg: 'bg-teal-950/60 text-teal-300 border-teal-500/40',
      arenaBorder: 'border-teal-500/40 focus-within:border-teal-400 focus-within:shadow-[0_0_25px_rgba(42,161,152,0.25)]',
      glow: 'shadow-[0_0_20px_rgba(42,161,152,0.2)]',
      glowEffect: 'shadow-[0_12px_36px_rgba(42,161,152,0.2)]',
      charDone: 'text-teal-300',
      charCurrent: 'text-amber-300 bg-teal-950/70 ring-2 ring-amber-400/80 shadow-[0_0_15px_rgba(181,137,0,0.5)]',
      cursor: 'bg-amber-400 shadow-[0_0_8px_#b58900]',
    },
  },
  nordic_ice: {
    id: 'nordic_ice',
    name: 'Nord Polar Frost',
    subtitle: 'Gelo Ártico & Aurora',
    description: 'Azuis polares glaciais com flocos de gelo geométricos e suave resplendor de aurora boreal.',
    price: 3,
    effectType: 'nordic_snow',
    previewColors: {
      bg: '#0b1118',
      card: '#131b26',
      accent: '#88c0d0',
      text: '#81a1c1',
    },
    classes: {
      appBg: 'bg-[#0b1118]',
      headerBg: 'bg-[#101824]/95 border-[#1d2d40]',
      cardBg: 'bg-[#131b26]',
      cardBorder: 'border-[#203248]',
      textPrimary: 'text-zinc-100',
      textSecondary: 'text-sky-300/80',
      textAccent: 'text-sky-300',
      accentBg: 'bg-sky-500/15',
      accentBorder: 'border-sky-500/40',
      badgeBg: 'bg-sky-950/60 text-sky-300 border-sky-500/40',
      arenaBorder: 'border-sky-500/40 focus-within:border-sky-400 focus-within:shadow-[0_0_25px_rgba(136,192,208,0.25)]',
      glow: 'shadow-[0_0_20px_rgba(136,192,208,0.2)]',
      glowEffect: 'shadow-[0_12px_36px_rgba(136,192,208,0.2)]',
      charDone: 'text-sky-300',
      charCurrent: 'text-cyan-200 bg-sky-950/70 ring-2 ring-cyan-300/80 shadow-[0_0_15px_rgba(136,192,208,0.5)]',
      cursor: 'bg-cyan-300 shadow-[0_0_8px_#88c0d0]',
    },
  },
  lava_terminal: {
    id: 'lava_terminal',
    name: 'Magma Hacker',
    subtitle: 'Vulcânico & Brasas',
    description: 'Obsidiana escura vulcânica com brasas quentes subindo e calor pulsante nos acertos.',
    price: 4,
    effectType: 'magma_embers',
    previewColors: {
      bg: '#140a08',
      card: '#22110c',
      accent: '#ea580c',
      text: '#f97316',
    },
    classes: {
      appBg: 'bg-[#140a08]',
      headerBg: 'bg-[#1c0e0b]/95 border-[#451c14]',
      cardBg: 'bg-[#22110c]',
      cardBorder: 'border-[#4c1e15]',
      textPrimary: 'text-zinc-100',
      textSecondary: 'text-orange-400/80',
      textAccent: 'text-orange-400',
      accentBg: 'bg-orange-500/15',
      accentBorder: 'border-orange-500/40',
      badgeBg: 'bg-orange-950/60 text-orange-300 border-orange-500/40',
      arenaBorder: 'border-orange-500/40 focus-within:border-orange-400 focus-within:shadow-[0_0_25px_rgba(234,88,12,0.3)]',
      glow: 'shadow-[0_0_20px_rgba(234,88,12,0.25)]',
      glowEffect: 'shadow-[0_12px_36px_rgba(234,88,12,0.25)]',
      charDone: 'text-orange-400',
      charCurrent: 'text-yellow-300 bg-orange-950/70 ring-2 ring-yellow-400/80 shadow-[0_0_15px_rgba(249,115,22,0.5)]',
      cursor: 'bg-orange-500 shadow-[0_0_8px_#ea580c]',
    },
  },
  golden_luxury: {
    id: 'golden_luxury',
    name: 'Mestre Dourado',
    subtitle: 'Glória Real Nível 100',
    description: 'Ouro nobre cintilante com partículas de pó estelar ascendentes reservado aos grandes mestres.',
    price: 15,
    currency: 'quantum_fragments',
    effectType: 'golden_sparkles',
    previewColors: {
      bg: '#120f06',
      card: '#201a0a',
      accent: '#eab308',
      text: '#fde047',
    },
    classes: {
      appBg: 'bg-[#120f06]',
      headerBg: 'bg-[#1b1507]/95 border-[#473812]',
      cardBg: 'bg-[#201a0a]',
      cardBorder: 'border-[#524115]',
      textPrimary: 'text-zinc-100',
      textSecondary: 'text-amber-300/80',
      textAccent: 'text-amber-300',
      accentBg: 'bg-amber-500/15',
      accentBorder: 'border-amber-500/40',
      badgeBg: 'bg-amber-950/60 text-amber-200 border-amber-500/40',
      arenaBorder: 'border-amber-500/50 focus-within:border-amber-300 focus-within:shadow-[0_0_28px_rgba(234,179,8,0.35)]',
      glow: 'shadow-[0_0_22px_rgba(234,179,8,0.25)]',
      glowEffect: 'shadow-[0_12px_36px_rgba(234,179,8,0.25)]',
      charDone: 'text-amber-300',
      charCurrent: 'text-yellow-100 bg-amber-950/70 ring-2 ring-yellow-300/80 shadow-[0_0_16px_rgba(253,224,71,0.5)]',
      cursor: 'bg-amber-300 shadow-[0_0_10px_#fde047]',
    },
  },
  stealth_mono: {
    id: 'stealth_mono',
    name: 'Terminal do Laboratório',
    subtitle: 'Colégio Leopoldina Pedroso',
    description: 'Verde menta oficial do Colégio e laboratório sobre preto absoluto com varredura CLI.',
    price: 2,
    effectType: 'mint_scanlines',
    previewColors: {
      bg: '#0a0d0c',
      card: '#101614',
      accent: '#87cf3e',
      text: '#98de4c',
    },
    classes: {
      appBg: 'bg-[#0a0d0c]',
      headerBg: 'bg-[#0e1412]/95 border-[#1b2b24]',
      cardBg: 'bg-[#101614]',
      cardBorder: 'border-[#1e3028]',
      textPrimary: 'text-zinc-100',
      textSecondary: 'text-emerald-300/80',
      textAccent: 'text-[#98de4c]',
      accentBg: 'bg-[#87cf3e]/15',
      accentBorder: 'border-[#87cf3e]/40',
      badgeBg: 'bg-emerald-950/60 text-emerald-200 border-emerald-500/40',
      arenaBorder: 'border-[#87cf3e]/40 focus-within:border-[#87cf3e] focus-within:shadow-[0_0_25px_rgba(135,207,62,0.25)]',
      glow: 'shadow-[0_0_20px_rgba(135,207,62,0.2)]',
      glowEffect: 'shadow-[0_12px_36px_rgba(135,207,62,0.2)]',
      charDone: 'text-[#98de4c]',
      charCurrent: 'text-white bg-emerald-950/70 ring-2 ring-[#87cf3e]/80 shadow-[0_0_15px_rgba(135,207,62,0.5)]',
      cursor: 'bg-[#87cf3e] shadow-[0_0_8px_#87cf3e]',
    },
  },
  sith_darkside: {
    id: 'sith_darkside',
    name: 'Lado Sombrio Sith',
    subtitle: 'Guerra nas Estrelas',
    description: 'Preto abissal com vermelho laser carmesim pulsante e faíscas de energia sombria.',
    price: 8,
    currency: 'duel_coins',
    effectType: 'sith_lightning',
    previewColors: {
      bg: '#080405',
      card: '#14080a',
      accent: '#ef4444',
      text: '#f87171',
    },
    classes: {
      appBg: 'bg-[#080405]',
      headerBg: 'bg-[#120608]/95 border-[#2c0d12]',
      cardBg: 'bg-[#14080a]',
      cardBorder: 'border-[#330f14]',
      textPrimary: 'text-zinc-100',
      textSecondary: 'text-red-300/80',
      textAccent: 'text-[#ef4444]',
      accentBg: 'bg-[#ef4444]/15',
      accentBorder: 'border-[#ef4444]/40',
      badgeBg: 'bg-red-950/60 text-red-200 border-red-500/40',
      arenaBorder: 'border-red-500/40 focus-within:border-red-500 focus-within:shadow-[0_0_25px_rgba(239,68,68,0.35)]',
      glow: 'shadow-[0_0_20px_rgba(239,68,68,0.25)]',
      glowEffect: 'shadow-[0_12px_36px_rgba(239,68,68,0.3)]',
      charDone: 'text-[#ef4444]',
      charCurrent: 'text-white bg-red-950/80 ring-2 ring-red-500 shadow-[0_0_20px_rgba(239,68,68,0.6)]',
      cursor: 'bg-[#ef4444] shadow-[0_0_10px_#ef4444]',
    },
  },
  super_saiyan: {
    id: 'super_saiyan',
    name: 'Aura Super Saiyajin',
    subtitle: 'Torneio Cósmico de Anime',
    description: 'Fundo azul-marinho profundo com texto ouro cintilante e Ki dourado flamejante.',
    price: 10,
    currency: 'duel_coins',
    effectType: 'saiyan_aura',
    previewColors: {
      bg: '#060b18',
      card: '#0c152a',
      accent: '#eab308',
      text: '#fde047',
    },
    classes: {
      appBg: 'bg-[#060b18]',
      headerBg: 'bg-[#0a1224]/95 border-[#1d2d4f]',
      cardBg: 'bg-[#0c152a]',
      cardBorder: 'border-[#1e325c]',
      textPrimary: 'text-zinc-100',
      textSecondary: 'text-amber-200/80',
      textAccent: 'text-[#fde047]',
      accentBg: 'bg-[#eab308]/15',
      accentBorder: 'border-[#eab308]/40',
      badgeBg: 'bg-amber-950/60 text-amber-200 border-amber-500/40',
      arenaBorder: 'border-amber-500/40 focus-within:border-amber-400 focus-within:shadow-[0_0_25px_rgba(234,179,8,0.35)]',
      glow: 'shadow-[0_0_20px_rgba(234,179,8,0.25)]',
      glowEffect: 'shadow-[0_12px_36px_rgba(234,179,8,0.3)]',
      charDone: 'text-[#fde047]',
      charCurrent: 'text-black bg-amber-400 ring-2 ring-amber-300 shadow-[0_0_20px_rgba(253,224,71,0.7)] font-bold',
      cursor: 'bg-[#fde047] shadow-[0_0_10px_#fde047]',
    },
  },
  nether_magma: {
    id: 'nether_magma',
    name: 'Profundezas do Nether',
    subtitle: 'Mundo Cúbico de Fogo',
    description: 'Obsidiana escura com lava incandescente, texto laranja fogo e brasas suspensas.',
    price: 8,
    currency: 'duel_coins',
    effectType: 'nether_flame',
    previewColors: {
      bg: '#0d0505',
      card: '#1c0b0b',
      accent: '#f97316',
      text: '#fb923c',
    },
    classes: {
      appBg: 'bg-[#0d0505]',
      headerBg: 'bg-[#180909]/95 border-[#3d1313]',
      cardBg: 'bg-[#1c0b0b]',
      cardBorder: 'border-[#421717]',
      textPrimary: 'text-zinc-100',
      textSecondary: 'text-orange-200/80',
      textAccent: 'text-[#fb923c]',
      accentBg: 'bg-[#f97316]/15',
      accentBorder: 'border-[#f97316]/40',
      badgeBg: 'bg-orange-950/60 text-orange-200 border-orange-500/40',
      arenaBorder: 'border-orange-500/40 focus-within:border-orange-500 focus-within:shadow-[0_0_25px_rgba(249,115,22,0.35)]',
      glow: 'shadow-[0_0_20px_rgba(249,115,22,0.25)]',
      glowEffect: 'shadow-[0_12px_36px_rgba(249,115,22,0.3)]',
      charDone: 'text-[#fb923c]',
      charCurrent: 'text-white bg-orange-950/80 ring-2 ring-orange-500 shadow-[0_0_20px_rgba(249,115,22,0.6)]',
      cursor: 'bg-[#f97316] shadow-[0_0_10px_#f97316]',
    },
  },
  spider_verse: {
    id: 'spider_verse',
    name: 'Dimensão Aracnídea',
    subtitle: 'Multiverso em Quadrinhos',
    description: 'Magenta e ciano fluorescentes sobre preto profundo com estilo graphic novel.',
    price: 10,
    currency: 'duel_coins',
    effectType: 'spider_web',
    previewColors: {
      bg: '#080812',
      card: '#121226',
      accent: '#ec4899',
      text: '#06b6d4',
    },
    classes: {
      appBg: 'bg-[#080812]',
      headerBg: 'bg-[#0d0d1f]/95 border-[#282852]',
      cardBg: 'bg-[#121226]',
      cardBorder: 'border-[#2d2d5c]',
      textPrimary: 'text-zinc-100',
      textSecondary: 'text-pink-300/80',
      textAccent: 'text-[#06b6d4]',
      accentBg: 'bg-[#ec4899]/15',
      accentBorder: 'border-[#ec4899]/40',
      badgeBg: 'bg-pink-950/60 text-pink-200 border-pink-500/40',
      arenaBorder: 'border-pink-500/40 focus-within:border-cyan-400 focus-within:shadow-[0_0_25px_rgba(6,182,212,0.35)]',
      glow: 'shadow-[0_0_20px_rgba(236,72,153,0.25)]',
      glowEffect: 'shadow-[0_12px_36px_rgba(6,182,212,0.3)]',
      charDone: 'text-[#06b6d4]',
      charCurrent: 'text-white bg-pink-950/80 ring-2 ring-pink-500 shadow-[0_0_20px_rgba(236,72,153,0.6)]',
      cursor: 'bg-[#06b6d4] shadow-[0_0_10px_#06b6d4]',
    },
  },
};

export interface SkinItemConfig {
  id: BytezinhoSkinId;
  name: string;
  subtitle: string;
  description: string;
  price: number;
  currency?: CosmeticCurrency;
  icon: string;
  tag: string;
  animationDescription: string;
}

export const BYTEZINHO_SKINS: Record<BytezinhoSkinId, SkinItemConfig> = {
  classic: {
    id: 'classic',
    name: 'Clássico CRT',
    subtitle: 'Padrão do Laboratório',
    description: 'O simpático monitor de tubo com fósforo verde e antena de recepção original.',
    price: 0,
    icon: '📺',
    tag: 'Padrão',
    animationDescription: 'Respiração suave e antena oscilante',
  },
  cyber: {
    id: 'cyber',
    name: 'Cibernético Neon',
    subtitle: 'Cyberpunk Visor',
    description: 'Visor de realidade aumentada com linhas neon e antena de comunicação de alta frequência.',
    price: 2,
    icon: '⚡',
    tag: 'Tecnológico',
    animationDescription: 'Jitter holográfico e sensor ótico pulsante',
  },
  retro_8bit: {
    id: 'retro_8bit',
    name: 'Retrô 8-Bits',
    subtitle: 'IBM PC 1981',
    description: 'Carcaça bege clássica com fendas de ventilação, entrada para disquete e visual nostálgico.',
    price: 3,
    icon: '💾',
    tag: 'Vintage',
    animationDescription: 'Passo escalonado 8-bit e LED ativo',
  },
  hoodie_hacker: {
    id: 'hoodie_hacker',
    name: 'Hacker com Capuz',
    subtitle: 'Modo Furtivo',
    description: 'Capuz escuro misterioso com sombras envolventes e olhar focado no código-fonte.',
    price: 3,
    icon: '🥷',
    tag: 'Furtivo',
    animationDescription: 'Respiração furtiva com sombras envolventes',
  },
  wizard: {
    id: 'wizard',
    name: 'Mago dos Códigos',
    subtitle: 'Arquimago do Algoritmo',
    description: 'Chapéu estrelado pontiagudo com aura mágica flutuante e feitiço sem bugs.',
    price: 4,
    icon: '🧙‍♂️',
    tag: 'Místico',
    animationDescription: 'Levitação mística ampla e faíscas estelares',
  },
  astronaut: {
    id: 'astronaut',
    name: 'Cosmonauta Espacial',
    subtitle: 'Gravidade Zero & Órbita',
    description: 'Traje pressurizado com capacete panorâmico, visor solar espelhado e tubo de oxigênio.',
    price: 4,
    icon: '🚀',
    tag: 'Espacial',
    animationDescription: 'Flutuação lenta em gravidade zero 360°',
  },
  ninja: {
    id: 'ninja',
    name: 'Shinobi Cibernético',
    subtitle: 'Guerreiro da Sombra',
    description: 'Bandana frontal com insígnia digital, máscara protetora ninja e reflexos rápidos.',
    price: 4,
    icon: '⚔️',
    tag: 'Ágil',
    animationDescription: 'Postura ágil e micro-dashes ultrarrápidos',
  },
  steampunk: {
    id: 'steampunk',
    name: 'Engenheiro Steampunk',
    subtitle: 'Mecânica a Vapor',
    description: 'Cartola vitoriana com óculos goggles de bronze, válvulas de escape e engrenagens.',
    price: 3,
    icon: '⚙️',
    tag: 'Vapor',
    animationDescription: 'Pulso mecânico de pistão e rotação de latão',
  },
  golden_king: {
    id: 'golden_king',
    name: 'Rei dos Bytes',
    subtitle: 'Coroa Imperial Nível 100',
    description: 'Coroa de ouro nobre com rubis lapidados, aura de realeza e brilho de prestígio imperial.',
    price: 20,
    currency: 'quantum_fragments',
    icon: '👑',
    tag: 'Quântico',
    animationDescription: 'Halo de luz dourada e postura majestosa',
  },
  diver: {
    id: 'diver',
    name: 'Mergulhador Abissal',
    subtitle: 'Exploração Submarina',
    description: 'Máscara aquática panorâmica com snorkel e bolhinhas de oxigênio ascendentes.',
    price: 3,
    icon: '🤿',
    tag: 'Aquático',
    animationDescription: 'Balanço aquático suave e bolhas subindo',
  },
  robot_mecha: {
    id: 'robot_mecha',
    name: 'Mecha de Defesa',
    subtitle: 'Blindagem Tática',
    description: 'Armadura reforçada de titânio com antenas de radar angulares e visor militar.',
    price: 4,
    icon: '🛡️',
    tag: 'Blindado',
    animationDescription: 'Varredura de radar tático e postura firme blindada',
  },
  jedi_master: {
    id: 'jedi_master',
    name: 'Mestre Jedi Bytezinho',
    subtitle: 'Cavaleiro da Força',
    description: 'Túnica de mestre estelar e sabre de luz de plasma esmeralda brilhante.',
    price: 8,
    currency: 'duel_coins',
    icon: '🧙‍♂️',
    tag: 'Jedi',
    animationDescription: 'Postura defensiva de sabre e lampejos de Força cósmica',
  },
  miner_diamond: {
    id: 'miner_diamond',
    name: 'Minerador Diamante',
    subtitle: 'Armadura Encantada',
    description: 'Elmo e armadura de diamante azul 16-bit com picareta de mineração pixelada.',
    price: 8,
    currency: 'duel_coins',
    icon: '⛏️',
    tag: 'Blocos',
    animationDescription: 'Batida rítmica de picareta e faíscas azuis de diamante',
  },
  saiyan_warrior: {
    id: 'saiyan_warrior',
    name: 'Guerreiro Saiyajin',
    subtitle: 'Poder Guerreiro Z',
    description: 'Cabelo dourado espetado Super Saiyajin com aura de ki amarela cintilante.',
    price: 10,
    currency: 'duel_coins',
    icon: '⚡',
    tag: 'Anime',
    animationDescription: 'Aura dourada ondulante e pulsação contínua de energia',
  },
  arachnid_hero: {
    id: 'arachnid_hero',
    name: 'Herói Aracnídeo',
    subtitle: 'Vigilante do Multiverso',
    description: 'Máscara com lentes brancas angulares e lançadores de teia cibernética.',
    price: 10,
    currency: 'duel_coins',
    icon: '🕸️',
    tag: 'Herói',
    animationDescription: 'Disparo ágil de teia e agilidade acrobática em alta velocidade',
  },
};

export interface KeySoundConfig {
  id: KeySoundThemeId;
  name: string;
  subtitle: string;
  description: string;
  price: number;
  currency?: CosmeticCurrency;
  icon: string;
  type: string;
}

export const KEY_SOUNDS: Record<KeySoundThemeId, KeySoundConfig> = {
  mechanical: {
    id: 'mechanical',
    name: 'Mecânico Clicky',
    subtitle: 'Switches Azuis Clássicos',
    description: 'Batida percussiva rápida e nítida com decaimento exponencial característico.',
    price: 0,
    icon: '⌨️',
    type: 'Triangular Rápida',
  },
  retro_beep: {
    id: 'retro_beep',
    name: 'Beep 8-Bit Arcade',
    subtitle: 'Chiptune Retro',
    description: 'Beeps sonoros em onda quadrada sintetizada, lembrando os jogos de Atari e fliperama.',
    price: 2,
    icon: '👾',
    type: 'Onda Quadrada',
  },
  typewriter: {
    id: 'typewriter',
    name: 'Máquina de Escrever',
    subtitle: 'Remington Mecânica',
    description: 'Estalo encorpado e firme com onda dente de serra simulando martelos de ferro no papel.',
    price: 3,
    icon: '📜',
    type: 'Dente de Serra',
  },
  soft_click: {
    id: 'soft_click',
    name: 'Clique Suave Soft',
    subtitle: 'Silencioso & Focado',
    description: 'Clique amortecido e aveludado em onda senoidal pura, ideal para máxima concentração.',
    price: 2,
    icon: '🎧',
    type: 'Senoidal Suave',
  },
  lightsaber_clash: {
    id: 'lightsaber_clash',
    name: 'Sabre Laser & Blaster',
    subtitle: 'Guerra nas Estrelas',
    description: 'Zumbido de plasma de sabre de luz e estalos de alta frequência ao digitar.',
    price: 6,
    currency: 'duel_coins',
    icon: '⚔️',
    type: 'Plasma Laser FM',
  },
  pixel_block_jump: {
    id: 'pixel_block_jump',
    name: 'Salto & Bloco Pixel',
    subtitle: 'Arcade Platformer',
    description: 'Sons percussivos de salto e impacto de quebra de bloco estilo videogame clássico.',
    price: 6,
    currency: 'duel_coins',
    icon: '🍄',
    type: 'Arpeggio Chiptune',
  },
  ki_blast: {
    id: 'ki_blast',
    name: 'Explosão de Ki',
    subtitle: 'Poder Guerreiro Z',
    description: 'Disparo percussivo de rajada de energia cósmica com decaimento ressonante.',
    price: 6,
    currency: 'duel_coins',
    icon: '⚡',
    type: 'Pulso de Energia Sub',
  },
};
