import { TerminalThemeId, BytezinhoSkinId, KeySoundThemeId, CosmeticCurrency } from '../types/cosmetics';

export interface TerminalThemeConfig {
  id: TerminalThemeId;
  name: string;
  subtitle: string;
  description: string;
  price: number;
  currency?: CosmeticCurrency;
  effectType:
    | 'matrix_rain'
    | 'dracula_mist'
    | 'amber_crt'
    | 'cyber_glitch'
    | 'monokai_code'
    | 'synthwave_grid'
    | 'solarized_waves'
    | 'nordic_snow'
    | 'magma_embers'
    | 'golden_sparkles'
    | 'mint_scanlines'
    | 'sith_lightning'
    | 'saiyan_aura'
    | 'nether_flame'
    | 'spider_web'
    | 'infinite_void_pulse'
    | 'gear_second_steam'
    | 'bad_time_retro'
    | 'sandevistan_grid'
    | 'sun_flame'
    | 'electric_storm'
    | 'serious_impact'
    | 'abyssal_glow'
    | 'supersonic_trail'
    | 'dark_sonar'
    | 'whatsapp_bubbles'
    | 'instagram_stories'
    | 'youtube_play'
    | 'tiktok_glitch'
    | 'roblox_grid';
  previewColors: {
    bg: string;
    card: string;
    accent: string;
    text: string;
  };
  classes: {
    appBg: string;
    headerBg: string;
    cardBg: string;
    cardBorder: string;
    textPrimary: string;
    textSecondary: string;
    textAccent: string;
    accentBg: string;
    accentBorder: string;
    badgeBg: string;
    arenaBorder: string;
    glow: string;
    glowEffect: string;
    charDone: string;
    charCurrent: string;
    cursor: string;
  };
}

export const TERMINAL_THEMES: Record<TerminalThemeId, TerminalThemeConfig> = {
  matrix: {
    id: 'matrix',
    name: 'Matrix Verde',
    subtitle: 'Terminal Clássico',
    description: 'Estilo clássico dos terminais de fósforo verde com caracteres em chuva digital.',
    price: 0,
    effectType: 'matrix_rain',
    previewColors: {
      bg: '#0a0d0a',
      card: '#0e140f',
      accent: '#10b981',
      text: '#34d399',
    },
    classes: {
      appBg: 'bg-[#0a0d0a]',
      headerBg: 'bg-[#0e140f]/95 border-[#1a2e1d]',
      cardBg: 'bg-[#0f1711]',
      cardBorder: 'border-[#1b3320]',
      textPrimary: 'text-zinc-100',
      textSecondary: 'text-emerald-400/80',
      textAccent: 'text-emerald-400',
      accentBg: 'bg-emerald-500/15',
      accentBorder: 'border-emerald-500/40',
      badgeBg: 'bg-emerald-950/60 text-emerald-300 border-emerald-500/40',
      arenaBorder: 'border-emerald-500/40 focus-within:border-emerald-400 focus-within:shadow-[0_0_25px_rgba(16,185,129,0.25)]',
      glow: 'shadow-[0_0_20px_rgba(16,185,129,0.2)]',
      glowEffect: 'shadow-[0_12px_36px_rgba(16,185,129,0.15)]',
      charDone: 'text-emerald-400',
      charCurrent: 'text-emerald-300 bg-emerald-950/60 ring-2 ring-emerald-400/80 shadow-[0_0_15px_rgba(16,185,129,0.4)]',
      cursor: 'bg-emerald-400 shadow-[0_0_8px_#10b981]',
    },
  },
  dracula: {
    id: 'dracula',
    name: 'Dracula Vamp',
    subtitle: 'Dark Violeta & Ciano',
    description: 'Paleta dark elegante com violeta escuro, fúcsia e névoa etérea pulsante.',
    price: 3,
    effectType: 'dracula_mist',
    previewColors: {
      bg: '#0d0b14',
      card: '#161224',
      accent: '#bd93f9',
      text: '#8be9fd',
    },
    classes: {
      appBg: 'bg-[#0d0b14]',
      headerBg: 'bg-[#151124]/95 border-[#2b214a]',
      cardBg: 'bg-[#161224]',
      cardBorder: 'border-[#2d224e]',
      textPrimary: 'text-zinc-100',
      textSecondary: 'text-purple-300/80',
      textAccent: 'text-purple-400',
      accentBg: 'bg-purple-500/15',
      accentBorder: 'border-purple-500/40',
      badgeBg: 'bg-purple-950/60 text-purple-300 border-purple-500/40',
      arenaBorder: 'border-purple-500/40 focus-within:border-purple-400 focus-within:shadow-[0_0_25px_rgba(168,85,247,0.25)]',
      glow: 'shadow-[0_0_20px_rgba(168,85,247,0.2)]',
      glowEffect: 'shadow-[0_12px_36px_rgba(168,85,247,0.18)]',
      charDone: 'text-purple-400',
      charCurrent: 'text-cyan-300 bg-purple-950/70 ring-2 ring-cyan-400/80 shadow-[0_0_15px_rgba(139,233,253,0.4)]',
      cursor: 'bg-cyan-400 shadow-[0_0_8px_#8be9fd]',
    },
  },
  amber: {
    id: 'amber',
    name: 'Fósforo Âmbar',
    subtitle: 'CRT Vintage 1982',
    description: 'Monitores mono-âmbar com feixe de varredura CRT e calor nostálgico dos primeiros PCs.',
    price: 2,
    effectType: 'amber_crt',
    previewColors: {
      bg: '#0f0c08',
      card: '#1c150c',
      accent: '#f59e0b',
      text: '#fbbf24',
    },
    classes: {
      appBg: 'bg-[#0f0c08]',
      headerBg: 'bg-[#1a130a]/95 border-[#382613]',
      cardBg: 'bg-[#1c150c]',
      cardBorder: 'border-[#3d2914]',
      textPrimary: 'text-zinc-100',
      textSecondary: 'text-amber-400/80',
      textAccent: 'text-amber-400',
      accentBg: 'bg-amber-500/15',
      accentBorder: 'border-amber-500/40',
      badgeBg: 'bg-amber-950/60 text-amber-300 border-amber-500/40',
      arenaBorder: 'border-amber-500/40 focus-within:border-amber-400 focus-within:shadow-[0_0_25px_rgba(245,158,11,0.25)]',
      glow: 'shadow-[0_0_20px_rgba(245,158,11,0.2)]',
      glowEffect: 'shadow-[0_12px_36px_rgba(245,158,11,0.2)]',
      charDone: 'text-amber-400',
      charCurrent: 'text-amber-200 bg-amber-950/70 ring-2 ring-amber-400/80 shadow-[0_0_15px_rgba(251,191,36,0.5)]',
      cursor: 'bg-amber-400 shadow-[0_0_8px_#fbbf24]',
    },
  },
  cyberpunk: {
    id: 'cyberpunk',
    name: 'Cyberpunk Neon',
    subtitle: 'High Tech, Night City',
    description: 'Amarelo cromo e azul ciano vibrante com feixes de circuitos eletrônicos pulsantes.',
    price: 4,
    effectType: 'cyber_glitch',
    previewColors: {
      bg: '#080c14',
      card: '#0c1524',
      accent: '#06b6d4',
      text: '#facc15',
    },
    classes: {
      appBg: 'bg-[#080c14]',
      headerBg: 'bg-[#0b1424]/95 border-[#162a4a]',
      cardBg: 'bg-[#0c1524]',
      cardBorder: 'border-[#182f54]',
      textPrimary: 'text-zinc-100',
      textSecondary: 'text-cyan-400/80',
      textAccent: 'text-cyan-400',
      accentBg: 'bg-cyan-500/15',
      accentBorder: 'border-cyan-500/40',
      badgeBg: 'bg-cyan-950/60 text-cyan-300 border-cyan-500/40',
      arenaBorder: 'border-cyan-500/40 focus-within:border-cyan-400 focus-within:shadow-[0_0_25px_rgba(6,182,212,0.25)]',
      glow: 'shadow-[0_0_20px_rgba(6,182,212,0.2)]',
      glowEffect: 'shadow-[0_12px_36px_rgba(6,182,212,0.25)]',
      charDone: 'text-cyan-400',
      charCurrent: 'text-yellow-300 bg-cyan-950/70 ring-2 ring-yellow-400/80 shadow-[0_0_15px_rgba(250,204,21,0.5)]',
      cursor: 'bg-yellow-400 shadow-[0_0_8px_#facc15]',
    },
  },
  monokai: {
    id: 'monokai',
    name: 'Monokai Pro',
    subtitle: 'IDE de Programação',
    description: 'Tema clássico de editores de código com tokens de programação flutuantes e sintaxe viva.',
    price: 3,
    effectType: 'monokai_code',
    previewColors: {
      bg: '#141512',
      card: '#1e1f1a',
      accent: '#a6e22e',
      text: '#f92672',
    },
    classes: {
      appBg: 'bg-[#141512]',
      headerBg: 'bg-[#1c1d17]/95 border-[#34362b]',
      cardBg: 'bg-[#1e1f1a]',
      cardBorder: 'border-[#383a2d]',
      textPrimary: 'text-zinc-100',
      textSecondary: 'text-lime-400/80',
      textAccent: 'text-lime-400',
      accentBg: 'bg-lime-500/15',
      accentBorder: 'border-lime-500/40',
      badgeBg: 'bg-lime-950/60 text-lime-300 border-lime-500/40',
      arenaBorder: 'border-lime-500/40 focus-within:border-lime-400 focus-within:shadow-[0_0_25px_rgba(163,230,53,0.25)]',
      glow: 'shadow-[0_0_20px_rgba(163,230,53,0.2)]',
      glowEffect: 'shadow-[0_12px_36px_rgba(163,230,53,0.18)]',
      charDone: 'text-lime-400',
      charCurrent: 'text-pink-300 bg-lime-950/60 ring-2 ring-pink-500/80 shadow-[0_0_15px_rgba(249,38,114,0.4)]',
      cursor: 'bg-pink-500 shadow-[0_0_8px_#f92672]',
    },
  },
  synthwave: {
    id: 'synthwave',
    name: 'Synthwave 84',
    subtitle: 'Outrun & Retrowave',
    description: 'Pôr-do-sol retrô futurista com grade de perspectiva ondulante em magenta e azul elétrico.',
    price: 4,
    effectType: 'synthwave_grid',
    previewColors: {
      bg: '#130a1e',
      card: '#1f1033',
      accent: '#f43f5e',
      text: '#38bdf8',
    },
    classes: {
      appBg: 'bg-[#130a1e]',
      headerBg: 'bg-[#1c0e2e]/95 border-[#421d66]',
      cardBg: 'bg-[#1f1033]',
      cardBorder: 'border-[#4a2273]',
      textPrimary: 'text-zinc-100',
      textSecondary: 'text-pink-400/80',
      textAccent: 'text-pink-400',
      accentBg: 'bg-pink-500/15',
      accentBorder: 'border-pink-500/40',
      badgeBg: 'bg-pink-950/60 text-pink-300 border-pink-500/40',
      arenaBorder: 'border-pink-500/40 focus-within:border-pink-400 focus-within:shadow-[0_0_25px_rgba(244,63,94,0.3)]',
      glow: 'shadow-[0_0_20px_rgba(244,63,94,0.25)]',
      glowEffect: 'shadow-[0_12px_36px_rgba(244,63,94,0.25)]',
      charDone: 'text-pink-400',
      charCurrent: 'text-cyan-300 bg-pink-950/70 ring-2 ring-cyan-400/80 shadow-[0_0_15px_rgba(56,189,248,0.5)]',
      cursor: 'bg-cyan-400 shadow-[0_0_8px_#38bdf8]',
    },
  },
  solarized_dark: {
    id: 'solarized_dark',
    name: 'Solarized Dark',
    subtitle: 'Harmonia Espectral',
    description: 'Oceano azul solar escuro com curvas harmônicas calmas e legibilidade científica suprema.',
    price: 3,
    effectType: 'solarized_waves',
    previewColors: {
      bg: '#001e26',
      card: '#073642',
      accent: '#2aa198',
      text: '#b58900',
    },
    classes: {
      appBg: 'bg-[#001e26]',
      headerBg: 'bg-[#042833]/95 border-[#0d4f61]',
      cardBg: 'bg-[#073642]',
      cardBorder: 'border-[#0e5264]',
      textPrimary: 'text-zinc-100',
      textSecondary: 'text-teal-300/80',
      textAccent: 'text-teal-300',
      accentBg: 'bg-teal-500/15',
      accentBorder: 'border-teal-500/40',
      badgeBg: 'bg-teal-950/60 text-teal-300 border-teal-500/40',
      arenaBorder: 'border-teal-500/40 focus-within:border-teal-400 focus-within:shadow-[0_0_25px_rgba(42,161,152,0.25)]',
      glow: 'shadow-[0_0_20px_rgba(42,161,152,0.2)]',
      glowEffect: 'shadow-[0_12px_36px_rgba(42,161,152,0.2)]',
      charDone: 'text-teal-300',
      charCurrent: 'text-amber-300 bg-teal-950/70 ring-2 ring-amber-400/80 shadow-[0_0_15px_rgba(181,137,0,0.5)]',
      cursor: 'bg-amber-400 shadow-[0_0_8px_#b58900]',
    },
  },
  nordic_ice: {
    id: 'nordic_ice',
    name: 'Nord Polar Frost',
    subtitle: 'Gelo Ártico & Aurora',
    description: 'Azuis polares glaciais com flocos de gelo geométricos e suave resplendor de aurora boreal.',
    price: 3,
    effectType: 'nordic_snow',
    previewColors: {
      bg: '#0b1118',
      card: '#131b26',
      accent: '#88c0d0',
      text: '#81a1c1',
    },
    classes: {
      appBg: 'bg-[#0b1118]',
      headerBg: 'bg-[#101824]/95 border-[#1d2d40]',
      cardBg: 'bg-[#131b26]',
      cardBorder: 'border-[#203248]',
      textPrimary: 'text-zinc-100',
      textSecondary: 'text-sky-300/80',
      textAccent: 'text-sky-300',
      accentBg: 'bg-sky-500/15',
      accentBorder: 'border-sky-500/40',
      badgeBg: 'bg-sky-950/60 text-sky-300 border-sky-500/40',
      arenaBorder: 'border-sky-500/40 focus-within:border-sky-400 focus-within:shadow-[0_0_25px_rgba(136,192,208,0.25)]',
      glow: 'shadow-[0_0_20px_rgba(136,192,208,0.2)]',
      glowEffect: 'shadow-[0_12px_36px_rgba(136,192,208,0.2)]',
      charDone: 'text-sky-300',
      charCurrent: 'text-cyan-200 bg-sky-950/70 ring-2 ring-cyan-300/80 shadow-[0_0_15px_rgba(136,192,208,0.5)]',
      cursor: 'bg-cyan-300 shadow-[0_0_8px_#88c0d0]',
    },
  },
  lava_terminal: {
    id: 'lava_terminal',
    name: 'Magma Hacker',
    subtitle: 'Vulcânico & Brasas',
    description: 'Obsidiana escura vulcânica com brasas quentes subindo e calor pulsante nos acertos.',
    price: 4,
    effectType: 'magma_embers',
    previewColors: {
      bg: '#140a08',
      card: '#22110c',
      accent: '#ea580c',
      text: '#f97316',
    },
    classes: {
      appBg: 'bg-[#140a08]',
      headerBg: 'bg-[#1c0e0b]/95 border-[#451c14]',
      cardBg: 'bg-[#22110c]',
      cardBorder: 'border-[#4c1e15]',
      textPrimary: 'text-zinc-100',
      textSecondary: 'text-orange-400/80',
      textAccent: 'text-orange-400',
      accentBg: 'bg-orange-500/15',
      accentBorder: 'border-orange-500/40',
      badgeBg: 'bg-orange-950/60 text-orange-300 border-orange-500/40',
      arenaBorder: 'border-orange-500/40 focus-within:border-orange-400 focus-within:shadow-[0_0_25px_rgba(234,88,12,0.3)]',
      glow: 'shadow-[0_0_20px_rgba(234,88,12,0.25)]',
      glowEffect: 'shadow-[0_12px_36px_rgba(234,88,12,0.25)]',
      charDone: 'text-orange-400',
      charCurrent: 'text-yellow-300 bg-orange-950/70 ring-2 ring-yellow-400/80 shadow-[0_0_15px_rgba(249,115,22,0.5)]',
      cursor: 'bg-orange-500 shadow-[0_0_8px_#ea580c]',
    },
  },
  golden_luxury: {
    id: 'golden_luxury',
    name: 'Mestre Dourado',
    subtitle: 'Glória Real Nível 100',
    description: 'Ouro nobre cintilante com partículas de pó estelar ascendentes reservado aos grandes mestres.',
    price: 15,
    currency: 'quantum_fragments',
    effectType: 'golden_sparkles',
    previewColors: {
      bg: '#120f06',
      card: '#201a0a',
      accent: '#eab308',
      text: '#fde047',
    },
    classes: {
      appBg: 'bg-[#120f06]',
      headerBg: 'bg-[#1b1507]/95 border-[#473812]',
      cardBg: 'bg-[#201a0a]',
      cardBorder: 'border-[#524115]',
      textPrimary: 'text-zinc-100',
      textSecondary: 'text-amber-300/80',
      textAccent: 'text-amber-300',
      accentBg: 'bg-amber-500/15',
      accentBorder: 'border-amber-500/40',
      badgeBg: 'bg-amber-950/60 text-amber-200 border-amber-500/40',
      arenaBorder: 'border-amber-500/50 focus-within:border-amber-300 focus-within:shadow-[0_0_28px_rgba(234,179,8,0.35)]',
      glow: 'shadow-[0_0_22px_rgba(234,179,8,0.25)]',
      glowEffect: 'shadow-[0_12px_36px_rgba(234,179,8,0.25)]',
      charDone: 'text-amber-300',
      charCurrent: 'text-yellow-100 bg-amber-950/70 ring-2 ring-yellow-300/80 shadow-[0_0_16px_rgba(253,224,71,0.5)]',
      cursor: 'bg-amber-300 shadow-[0_0_10px_#fde047]',
    },
  },
  stealth_mono: {
    id: 'stealth_mono',
    name: 'Terminal do Laboratório',
    subtitle: 'Colégio Leopoldina Pedroso',
    description: 'Verde menta oficial do Colégio e laboratório sobre preto absoluto com varredura CLI.',
    price: 2,
    effectType: 'mint_scanlines',
    previewColors: {
      bg: '#0a0d0c',
      card: '#101614',
      accent: '#87cf3e',
      text: '#98de4c',
    },
    classes: {
      appBg: 'bg-[#0a0d0c]',
      headerBg: 'bg-[#0e1412]/95 border-[#1b2b24]',
      cardBg: 'bg-[#101614]',
      cardBorder: 'border-[#1e3028]',
      textPrimary: 'text-zinc-100',
      textSecondary: 'text-emerald-300/80',
      textAccent: 'text-[#98de4c]',
      accentBg: 'bg-[#87cf3e]/15',
      accentBorder: 'border-[#87cf3e]/40',
      badgeBg: 'bg-emerald-950/60 text-emerald-200 border-emerald-500/40',
      arenaBorder: 'border-[#87cf3e]/40 focus-within:border-[#87cf3e] focus-within:shadow-[0_0_25px_rgba(135,207,62,0.25)]',
      glow: 'shadow-[0_0_20px_rgba(135,207,62,0.2)]',
      glowEffect: 'shadow-[0_12px_36px_rgba(135,207,62,0.2)]',
      charDone: 'text-[#98de4c]',
      charCurrent: 'text-white bg-emerald-950/70 ring-2 ring-[#87cf3e]/80 shadow-[0_0_15px_rgba(135,207,62,0.5)]',
      cursor: 'bg-[#87cf3e] shadow-[0_0_8px_#87cf3e]',
    },
  },
  sith_darkside: {
    id: 'sith_darkside',
    name: 'Lado Sombrio Sith',
    subtitle: 'Guerra nas Estrelas',
    description: 'Preto abissal com vermelho laser carmesim pulsante e faíscas de energia sombria.',
    price: 8,
    currency: 'duel_coins',
    effectType: 'sith_lightning',
    previewColors: {
      bg: '#080405',
      card: '#14080a',
      accent: '#ef4444',
      text: '#f87171',
    },
    classes: {
      appBg: 'bg-[#080405]',
      headerBg: 'bg-[#120608]/95 border-[#2c0d12]',
      cardBg: 'bg-[#14080a]',
      cardBorder: 'border-[#330f14]',
      textPrimary: 'text-zinc-100',
      textSecondary: 'text-red-300/80',
      textAccent: 'text-[#ef4444]',
      accentBg: 'bg-[#ef4444]/15',
      accentBorder: 'border-[#ef4444]/40',
      badgeBg: 'bg-red-950/60 text-red-200 border-red-500/40',
      arenaBorder: 'border-red-500/40 focus-within:border-red-500 focus-within:shadow-[0_0_25px_rgba(239,68,68,0.35)]',
      glow: 'shadow-[0_0_20px_rgba(239,68,68,0.25)]',
      glowEffect: 'shadow-[0_12px_36px_rgba(239,68,68,0.3)]',
      charDone: 'text-[#ef4444]',
      charCurrent: 'text-white bg-red-950/80 ring-2 ring-red-500 shadow-[0_0_20px_rgba(239,68,68,0.6)]',
      cursor: 'bg-[#ef4444] shadow-[0_0_10px_#ef4444]',
    },
  },
  super_saiyan: {
    id: 'super_saiyan',
    name: 'Aura Super Saiyajin',
    subtitle: 'Torneio Cósmico de Anime',
    description: 'Fundo azul-marinho profundo com texto ouro cintilante e Ki dourado flamejante.',
    price: 10,
    currency: 'duel_coins',
    effectType: 'saiyan_aura',
    previewColors: {
      bg: '#060b18',
      card: '#0c152a',
      accent: '#eab308',
      text: '#fde047',
    },
    classes: {
      appBg: 'bg-[#060b18]',
      headerBg: 'bg-[#0a1224]/95 border-[#1d2d4f]',
      cardBg: 'bg-[#0c152a]',
      cardBorder: 'border-[#1e325c]',
      textPrimary: 'text-zinc-100',
      textSecondary: 'text-amber-200/80',
      textAccent: 'text-[#fde047]',
      accentBg: 'bg-[#eab308]/15',
      accentBorder: 'border-[#eab308]/40',
      badgeBg: 'bg-amber-950/60 text-amber-200 border-amber-500/40',
      arenaBorder: 'border-amber-500/40 focus-within:border-amber-400 focus-within:shadow-[0_0_25px_rgba(234,179,8,0.35)]',
      glow: 'shadow-[0_0_20px_rgba(234,179,8,0.25)]',
      glowEffect: 'shadow-[0_12px_36px_rgba(234,179,8,0.3)]',
      charDone: 'text-[#fde047]',
      charCurrent: 'text-black bg-amber-400 ring-2 ring-amber-300 shadow-[0_0_20px_rgba(253,224,71,0.7)] font-bold',
      cursor: 'bg-[#fde047] shadow-[0_0_10px_#fde047]',
    },
  },
  nether_magma: {
    id: 'nether_magma',
    name: 'Profundezas do Nether',
    subtitle: 'Mundo Cúbico de Fogo',
    description: 'Obsidiana escura com lava incandescente, texto laranja fogo e brasas suspensas.',
    price: 8,
    currency: 'duel_coins',
    effectType: 'nether_flame',
    previewColors: {
      bg: '#0d0505',
      card: '#1c0b0b',
      accent: '#f97316',
      text: '#fb923c',
    },
    classes: {
      appBg: 'bg-[#0d0505]',
      headerBg: 'bg-[#180909]/95 border-[#3d1313]',
      cardBg: 'bg-[#1c0b0b]',
      cardBorder: 'border-[#421717]',
      textPrimary: 'text-zinc-100',
      textSecondary: 'text-orange-200/80',
      textAccent: 'text-[#fb923c]',
      accentBg: 'bg-[#f97316]/15',
      accentBorder: 'border-[#f97316]/40',
      badgeBg: 'bg-orange-950/60 text-orange-200 border-orange-500/40',
      arenaBorder: 'border-orange-500/40 focus-within:border-orange-500 focus-within:shadow-[0_0_25px_rgba(249,115,22,0.35)]',
      glow: 'shadow-[0_0_20px_rgba(249,115,22,0.25)]',
      glowEffect: 'shadow-[0_12px_36px_rgba(249,115,22,0.3)]',
      charDone: 'text-[#fb923c]',
      charCurrent: 'text-white bg-orange-950/80 ring-2 ring-orange-500 shadow-[0_0_20px_rgba(249,115,22,0.6)]',
      cursor: 'bg-[#f97316] shadow-[0_0_10px_#f97316]',
    },
  },
  spider_verse: {
    id: 'spider_verse',
    name: 'Dimensão Aracnídea',
    subtitle: 'Multiverso em Quadrinhos',
    description: 'Magenta e ciano fluorescentes sobre preto profundo com estilo graphic novel.',
    price: 10,
    currency: 'duel_coins',
    effectType: 'spider_web',
    previewColors: {
      bg: '#080812',
      card: '#121226',
      accent: '#ec4899',
      text: '#06b6d4',
    },
    classes: {
      appBg: 'bg-[#080812]',
      headerBg: 'bg-[#0d0d1f]/95 border-[#282852]',
      cardBg: 'bg-[#121226]',
      cardBorder: 'border-[#2d2d5c]',
      textPrimary: 'text-zinc-100',
      textSecondary: 'text-pink-300/80',
      textAccent: 'text-[#06b6d4]',
      accentBg: 'bg-[#ec4899]/15',
      accentBorder: 'border-[#ec4899]/40',
      badgeBg: 'bg-pink-950/60 text-pink-200 border-pink-500/40',
      arenaBorder: 'border-pink-500/40 focus-within:border-cyan-400 focus-within:shadow-[0_0_25px_rgba(6,182,212,0.35)]',
      glow: 'shadow-[0_0_20px_rgba(236,72,153,0.25)]',
      glowEffect: 'shadow-[0_12px_36px_rgba(6,182,212,0.3)]',
      charDone: 'text-[#06b6d4]',
      charCurrent: 'text-white bg-pink-950/80 ring-2 ring-pink-500 shadow-[0_0_20px_rgba(236,72,153,0.6)]',
      cursor: 'bg-[#06b6d4] shadow-[0_0_10px_#06b6d4]',
    },
  },
  infinite_void: {
    id: 'infinite_void',
    name: 'Vazio Infinito',
    subtitle: 'Domínio do Feiticeiro Vendado',
    description: 'Preto cósmico estelar com caracteres em ciano radiante e distorção gravitacional pura.',
    price: 42,
    currency: 'quantum_fragments',
    effectType: 'infinite_void_pulse',
    previewColors: {
      bg: '#020208',
      card: '#080816',
      accent: '#38bdf8',
      text: '#e0f2fe',
    },
    classes: {
      appBg: 'bg-[#020208]',
      headerBg: 'bg-[#050512]/95 border-[#1e1b4b]',
      cardBg: 'bg-[#080816]',
      cardBorder: 'border-[#1e293b]',
      textPrimary: 'text-zinc-50',
      textSecondary: 'text-cyan-300/85',
      textAccent: 'text-[#38bdf8]',
      accentBg: 'bg-cyan-500/20',
      accentBorder: 'border-cyan-400/50',
      badgeBg: 'bg-cyan-950/70 text-cyan-200 border-cyan-400/50',
      arenaBorder: 'border-cyan-400/50 focus-within:border-cyan-300 focus-within:shadow-[0_0_35px_rgba(56,189,248,0.45)]',
      glow: 'shadow-[0_0_25px_rgba(56,189,248,0.35)]',
      glowEffect: 'shadow-[0_12px_40px_rgba(56,189,248,0.35)]',
      charDone: 'text-[#38bdf8]',
      charCurrent: 'text-black bg-cyan-300 ring-2 ring-cyan-100 shadow-[0_0_25px_rgba(56,189,248,0.9)] font-bold',
      cursor: 'bg-cyan-300 shadow-[0_0_12px_#38bdf8]',
    },
  },
  gear_second: {
    id: 'gear_second',
    name: 'Segunda Marcha Escarlate',
    subtitle: 'Vapor do Pirata Emborrachado',
    description: 'Vermelho carmesim e rosa vapor com pulsação sanguínea de alta velocidade.',
    price: 38,
    currency: 'quantum_fragments',
    effectType: 'gear_second_steam',
    previewColors: {
      bg: '#140407',
      card: '#22080d',
      accent: '#f43f5e',
      text: '#fecdd3',
    },
    classes: {
      appBg: 'bg-[#140407]',
      headerBg: 'bg-[#1a050a]/95 border-[#4c0519]',
      cardBg: 'bg-[#22080d]',
      cardBorder: 'border-[#5c0b1e]',
      textPrimary: 'text-zinc-50',
      textSecondary: 'text-rose-300/85',
      textAccent: 'text-[#f43f5e]',
      accentBg: 'bg-rose-500/20',
      accentBorder: 'border-rose-400/50',
      badgeBg: 'bg-rose-950/70 text-rose-200 border-rose-400/50',
      arenaBorder: 'border-rose-500/50 focus-within:border-rose-400 focus-within:shadow-[0_0_35px_rgba(244,63,94,0.45)]',
      glow: 'shadow-[0_0_25px_rgba(244,63,94,0.35)]',
      glowEffect: 'shadow-[0_12px_40px_rgba(244,63,94,0.35)]',
      charDone: 'text-[#f43f5e]',
      charCurrent: 'text-white bg-rose-950/90 ring-2 ring-rose-400 shadow-[0_0_25px_rgba(244,63,94,0.8)] font-bold',
      cursor: 'bg-rose-400 shadow-[0_0_12px_#f43f5e]',
    },
  },
  bad_time_retro: {
    id: 'bad_time_retro',
    name: 'Salão do Julgamento Retrô',
    subtitle: 'Megalovânia do Esqueleto',
    description: 'Preto e branco puro de 1-bit com olho esquerdo em fogo ciano-azul reluzente.',
    price: 40,
    currency: 'quantum_fragments',
    effectType: 'bad_time_retro',
    previewColors: {
      bg: '#050505',
      card: '#121212',
      accent: '#06b6d4',
      text: '#ffffff',
    },
    classes: {
      appBg: 'bg-[#050505]',
      headerBg: 'bg-[#0f0f0f]/95 border-[#262626]',
      cardBg: 'bg-[#121212]',
      cardBorder: 'border-[#2e2e2e]',
      textPrimary: 'text-white',
      textSecondary: 'text-zinc-300',
      textAccent: 'text-[#06b6d4]',
      accentBg: 'bg-cyan-500/15',
      accentBorder: 'border-cyan-400/50',
      badgeBg: 'bg-zinc-900 text-cyan-300 border-cyan-500/40',
      arenaBorder: 'border-cyan-400/50 focus-within:border-cyan-300 focus-within:shadow-[0_0_30px_rgba(6,182,212,0.4)]',
      glow: 'shadow-[0_0_20px_rgba(6,182,212,0.3)]',
      glowEffect: 'shadow-[0_12px_36px_rgba(6,182,212,0.3)]',
      charDone: 'text-[#06b6d4]',
      charCurrent: 'text-black bg-white ring-2 ring-cyan-400 shadow-[0_0_25px_rgba(6,182,212,0.8)] font-bold',
      cursor: 'bg-cyan-400 shadow-[0_0_12px_#06b6d4]',
    },
  },
  sandevistan_overdrive: {
    id: 'sandevistan_overdrive',
    name: 'Sandevistan Overdrive',
    subtitle: 'Ciborgue Urbano 2077',
    description: 'Amarelo militar de alta saturação com ciano de sobrecarga e rastro temporal.',
    price: 44,
    currency: 'quantum_fragments',
    effectType: 'sandevistan_grid',
    previewColors: {
      bg: '#0a0d02',
      card: '#161a05',
      accent: '#eab308',
      text: '#06b6d4',
    },
    classes: {
      appBg: 'bg-[#0a0d02]',
      headerBg: 'bg-[#121603]/95 border-[#2e3809]',
      cardBg: 'bg-[#161a05]',
      cardBorder: 'border-[#3f4d0c]',
      textPrimary: 'text-zinc-100',
      textSecondary: 'text-yellow-300/85',
      textAccent: 'text-[#eab308]',
      accentBg: 'bg-yellow-500/20',
      accentBorder: 'border-yellow-400/50',
      badgeBg: 'bg-yellow-950/70 text-yellow-300 border-yellow-400/50',
      arenaBorder: 'border-yellow-400/50 focus-within:border-cyan-400 focus-within:shadow-[0_0_35px_rgba(234,179,8,0.45)]',
      glow: 'shadow-[0_0_25px_rgba(234,179,8,0.35)]',
      glowEffect: 'shadow-[0_12px_40px_rgba(234,179,8,0.35)]',
      charDone: 'text-[#eab308]',
      charCurrent: 'text-black bg-yellow-300 ring-2 ring-cyan-400 shadow-[0_0_25px_rgba(6,182,212,0.8)] font-bold',
      cursor: 'bg-yellow-300 shadow-[0_0_12px_#eab308]',
    },
  },
  sun_breathing: {
    id: 'sun_breathing',
    name: 'Dança do Deus do Fogo',
    subtitle: 'Caçador do Quimono Xadrez',
    description: 'Gradiente de chamas solares laranjas sobre nanquim com estilo de xilogravura.',
    price: 39,
    currency: 'quantum_fragments',
    effectType: 'sun_flame',
    previewColors: {
      bg: '#120502',
      card: '#220b04',
      accent: '#f97316',
      text: '#fdba74',
    },
    classes: {
      appBg: 'bg-[#120502]',
      headerBg: 'bg-[#1a0703]/95 border-[#431407]',
      cardBg: 'bg-[#220b04]',
      cardBorder: 'border-[#541c0a]',
      textPrimary: 'text-zinc-50',
      textSecondary: 'text-orange-300/85',
      textAccent: 'text-[#f97316]',
      accentBg: 'bg-orange-500/20',
      accentBorder: 'border-orange-400/50',
      badgeBg: 'bg-orange-950/70 text-orange-200 border-orange-400/50',
      arenaBorder: 'border-orange-500/50 focus-within:border-orange-400 focus-within:shadow-[0_0_35px_rgba(249,115,22,0.45)]',
      glow: 'shadow-[0_0_25px_rgba(249,115,22,0.35)]',
      glowEffect: 'shadow-[0_12px_40px_rgba(249,115,22,0.35)]',
      charDone: 'text-[#f97316]',
      charCurrent: 'text-black bg-orange-400 ring-2 ring-yellow-300 shadow-[0_0_25px_rgba(249,115,22,0.8)] font-bold',
      cursor: 'bg-orange-400 shadow-[0_0_12px_#f97316]',
    },
  },
  electric_thunder: {
    id: 'electric_thunder',
    name: 'Trovão 100k Volts',
    subtitle: 'Roedor Elétrico Lendário',
    description: 'Amarelo elétrico e faíscas azuis em console clássico portátil.',
    price: 36,
    currency: 'quantum_fragments',
    effectType: 'electric_storm',
    previewColors: {
      bg: '#0c0d06',
      card: '#181a0c',
      accent: '#facc15',
      text: '#fef08a',
    },
    classes: {
      appBg: 'bg-[#0c0d06]',
      headerBg: 'bg-[#141609]/95 border-[#323614]',
      cardBg: 'bg-[#181a0c]',
      cardBorder: 'border-[#414619]',
      textPrimary: 'text-zinc-50',
      textSecondary: 'text-yellow-200/85',
      textAccent: 'text-[#facc15]',
      accentBg: 'bg-yellow-500/20',
      accentBorder: 'border-yellow-400/50',
      badgeBg: 'bg-yellow-950/70 text-yellow-200 border-yellow-400/50',
      arenaBorder: 'border-yellow-400/50 focus-within:border-yellow-300 focus-within:shadow-[0_0_35px_rgba(250,204,21,0.45)]',
      glow: 'shadow-[0_0_25px_rgba(250,204,21,0.35)]',
      glowEffect: 'shadow-[0_12px_40px_rgba(250,204,21,0.35)]',
      charDone: 'text-[#facc15]',
      charCurrent: 'text-black bg-yellow-300 ring-2 ring-yellow-100 shadow-[0_0_25px_rgba(250,204,21,0.85)] font-bold',
      cursor: 'bg-yellow-300 shadow-[0_0_12px_#facc15]',
    },
  },
  serious_punch: {
    id: 'serious_punch',
    name: 'Golpe Sério Supremo',
    subtitle: 'Herói por Passatempo',
    description: 'Estética de mangá com traço hiper-detalhado, vermelho de impacto e branco estelar.',
    price: 46,
    currency: 'quantum_fragments',
    effectType: 'serious_impact',
    previewColors: {
      bg: '#08080a',
      card: '#141418',
      accent: '#ef4444',
      text: '#fef2f2',
    },
    classes: {
      appBg: 'bg-[#08080a]',
      headerBg: 'bg-[#101014]/95 border-[#27272a]',
      cardBg: 'bg-[#141418]',
      cardBorder: 'border-[#3f3f46]',
      textPrimary: 'text-zinc-50',
      textSecondary: 'text-red-300/85',
      textAccent: 'text-[#ef4444]',
      accentBg: 'bg-red-500/20',
      accentBorder: 'border-red-400/50',
      badgeBg: 'bg-red-950/70 text-red-200 border-red-400/50',
      arenaBorder: 'border-red-500/50 focus-within:border-red-400 focus-within:shadow-[0_0_35px_rgba(239,68,68,0.45)]',
      glow: 'shadow-[0_0_25px_rgba(239,68,68,0.35)]',
      glowEffect: 'shadow-[0_12px_40px_rgba(239,68,68,0.35)]',
      charDone: 'text-[#ef4444]',
      charCurrent: 'text-white bg-red-600 ring-2 ring-white shadow-[0_0_25px_rgba(239,68,68,0.85)] font-bold',
      cursor: 'bg-red-500 shadow-[0_0_12px_#ef4444]',
    },
  },
  abyssal_vessel: {
    id: 'abyssal_vessel',
    name: 'Reino do Vazio Abissal',
    subtitle: 'Besouro Agulheiro de Hallownest',
    description: 'Azul-marinho escuro e gotas de Alma cintilantes em ambiente gótico etéreo.',
    price: 41,
    currency: 'quantum_fragments',
    effectType: 'abyssal_glow',
    previewColors: {
      bg: '#050a12',
      card: '#0c1524',
      accent: '#7dd3fc',
      text: '#f0f9ff',
    },
    classes: {
      appBg: 'bg-[#050a12]',
      headerBg: 'bg-[#09101e]/95 border-[#172554]',
      cardBg: 'bg-[#0c1524]',
      cardBorder: 'border-[#1e3a5f]',
      textPrimary: 'text-zinc-50',
      textSecondary: 'text-sky-200/85',
      textAccent: 'text-[#7dd3fc]',
      accentBg: 'bg-sky-500/20',
      accentBorder: 'border-sky-400/50',
      badgeBg: 'bg-sky-950/70 text-sky-200 border-sky-400/50',
      arenaBorder: 'border-sky-400/50 focus-within:border-sky-300 focus-within:shadow-[0_0_35px_rgba(125,211,252,0.45)]',
      glow: 'shadow-[0_0_25px_rgba(125,211,252,0.35)]',
      glowEffect: 'shadow-[0_12px_40px_rgba(125,211,252,0.35)]',
      charDone: 'text-[#7dd3fc]',
      charCurrent: 'text-black bg-sky-200 ring-2 ring-white shadow-[0_0_25px_rgba(125,211,252,0.85)] font-bold',
      cursor: 'bg-sky-300 shadow-[0_0_12px_#7dd3fc]',
    },
  },
  supersonic_speed: {
    id: 'supersonic_speed',
    name: 'Colinas Esmeralda 16-Bit',
    subtitle: 'Ouriço Supersônico',
    description: 'Azul cobalto ultra sônico e verde esmeralda com anéis dourados giratórios.',
    price: 37,
    currency: 'quantum_fragments',
    effectType: 'supersonic_trail',
    previewColors: {
      bg: '#030a1c',
      card: '#091538',
      accent: '#38bdf8',
      text: '#fde047',
    },
    classes: {
      appBg: 'bg-[#030a1c]',
      headerBg: 'bg-[#06102a]/95 border-[#1e3a8a]',
      cardBg: 'bg-[#091538]',
      cardBorder: 'border-[#1d4ed8]',
      textPrimary: 'text-zinc-50',
      textSecondary: 'text-yellow-300/85',
      textAccent: 'text-[#fde047]',
      accentBg: 'bg-blue-500/20',
      accentBorder: 'border-blue-400/50',
      badgeBg: 'bg-blue-950/70 text-yellow-300 border-blue-400/50',
      arenaBorder: 'border-blue-500/50 focus-within:border-yellow-400 focus-within:shadow-[0_0_35px_rgba(56,189,248,0.45)]',
      glow: 'shadow-[0_0_25px_rgba(56,189,248,0.35)]',
      glowEffect: 'shadow-[0_12px_40px_rgba(56,189,248,0.35)]',
      charDone: 'text-[#fde047]',
      charCurrent: 'text-black bg-yellow-300 ring-2 ring-blue-400 shadow-[0_0_25px_rgba(253,224,71,0.85)] font-bold',
      cursor: 'bg-yellow-300 shadow-[0_0_12px_#fde047]',
    },
  },
  dark_detective: {
    id: 'dark_detective',
    name: 'Caverna Tática Noturna',
    subtitle: 'Cavaleiro das Sombras',
    description: 'Grafite militar blindado com tela âmbar e sonar tático de morcego.',
    price: 40,
    currency: 'quantum_fragments',
    effectType: 'dark_sonar',
    previewColors: {
      bg: '#08080a',
      card: '#121216',
      accent: '#f59e0b',
      text: '#fbbf24',
    },
    classes: {
      appBg: 'bg-[#08080a]',
      headerBg: 'bg-[#0c0c10]/95 border-[#27272a]',
      cardBg: 'bg-[#121216]',
      cardBorder: 'border-[#27272a]',
      textPrimary: 'text-zinc-50',
      textSecondary: 'text-amber-300/85',
      textAccent: 'text-[#f59e0b]',
      accentBg: 'bg-amber-500/20',
      accentBorder: 'border-amber-400/50',
      badgeBg: 'bg-amber-950/70 text-amber-300 border-amber-400/50',
      arenaBorder: 'border-amber-500/50 focus-within:border-amber-400 focus-within:shadow-[0_0_35px_rgba(245,158,11,0.45)]',
      glow: 'shadow-[0_0_25px_rgba(245,158,11,0.35)]',
      glowEffect: 'shadow-[0_12px_40px_rgba(245,158,11,0.35)]',
      charDone: 'text-[#f59e0b]',
      charCurrent: 'text-black bg-amber-400 ring-2 ring-amber-200 shadow-[0_0_25px_rgba(245,158,11,0.85)] font-bold',
      cursor: 'bg-amber-400 shadow-[0_0_12px_#f59e0b]',
    },
  },
  whatsapp_chat: {
    id: 'whatsapp_chat',
    name: 'Zap Mensagens',
    subtitle: 'Chat & Notificações Verdes',
    description: 'Visual inspirado no app de mensagens com verde esmeralda icônico, balões escuros e ticks de confirmação.',
    price: 5,
    currency: 'tokens',
    effectType: 'whatsapp_bubbles',
    previewColors: {
      bg: '#0b141a',
      card: '#111b21',
      accent: '#25d366',
      text: '#53bdeb',
    },
    classes: {
      appBg: 'bg-[#0b141a]',
      headerBg: 'bg-[#111b21]/95 border-[#202c33]',
      cardBg: 'bg-[#111b21]',
      cardBorder: 'border-[#202c33]',
      textPrimary: 'text-[#e9edef]',
      textSecondary: 'text-[#8696a0]',
      textAccent: 'text-[#25d366]',
      accentBg: 'bg-[#25d366]/15',
      accentBorder: 'border-[#25d366]/40',
      badgeBg: 'bg-[#005c4b]/50 text-[#25d366] border-[#25d366]/40',
      arenaBorder: 'border-[#25d366]/40 focus-within:border-[#25d366] focus-within:shadow-[0_0_25px_rgba(37,211,102,0.3)]',
      glow: 'shadow-[0_0_20px_rgba(37,211,102,0.2)]',
      glowEffect: 'shadow-[0_12px_36px_rgba(37,211,102,0.25)]',
      charDone: 'text-[#25d366]',
      charCurrent: 'text-white bg-[#005c4b]/80 ring-2 ring-[#25d366] shadow-[0_0_18px_rgba(37,211,102,0.6)]',
      cursor: 'bg-[#25d366] shadow-[0_0_10px_#25d366]',
    },
  },
  instagram_gradient: {
    id: 'instagram_gradient',
    name: 'Insta Stories',
    subtitle: 'Sunset & Gradiente Stories',
    description: 'Estilo moderno com gradiente dinâmico de magenta, púrpura e dourado pôr-do-sol com anéis em néon.',
    price: 6,
    currency: 'tokens',
    effectType: 'instagram_stories',
    previewColors: {
      bg: '#0c0614',
      card: '#170d24',
      accent: '#e1306c',
      text: '#f77737',
    },
    classes: {
      appBg: 'bg-[#0c0614]',
      headerBg: 'bg-[#170d24]/95 border-[#301646]',
      cardBg: 'bg-[#170d24]',
      cardBorder: 'border-[#301646]',
      textPrimary: 'text-zinc-100',
      textSecondary: 'text-pink-300/80',
      textAccent: 'text-[#e1306c]',
      accentBg: 'bg-[#e1306c]/15',
      accentBorder: 'border-[#e1306c]/40',
      badgeBg: 'bg-pink-950/60 text-pink-300 border-pink-500/40',
      arenaBorder: 'border-[#e1306c]/50 focus-within:border-[#f77737] focus-within:shadow-[0_0_25px_rgba(225,48,108,0.35)]',
      glow: 'shadow-[0_0_20px_rgba(225,48,108,0.25)]',
      glowEffect: 'shadow-[0_12px_36px_rgba(225,48,108,0.3)]',
      charDone: 'text-[#e1306c]',
      charCurrent: 'text-white bg-pink-950/80 ring-2 ring-[#f77737] shadow-[0_0_20px_rgba(225,48,108,0.6)]',
      cursor: 'bg-[#f77737] shadow-[0_0_10px_#f77737]',
    },
  },
  youtube_creator: {
    id: 'youtube_creator',
    name: 'Tube Player',
    subtitle: 'Play Button & Cinema Escuro',
    description: 'Inspirado no visual cinematográfico de vídeos com vermelho rubi marcante, cartões grafite e barras de play.',
    price: 5,
    currency: 'tokens',
    effectType: 'youtube_play',
    previewColors: {
      bg: '#0f0f0f',
      card: '#1f1f1f',
      accent: '#ff0000',
      text: '#ffffff',
    },
    classes: {
      appBg: 'bg-[#0f0f0f]',
      headerBg: 'bg-[#181818]/95 border-[#2b2b2b]',
      cardBg: 'bg-[#1f1f1f]',
      cardBorder: 'border-[#333333]',
      textPrimary: 'text-zinc-100',
      textSecondary: 'text-zinc-400',
      textAccent: 'text-[#ff0000]',
      accentBg: 'bg-[#ff0000]/15',
      accentBorder: 'border-[#ff0000]/40',
      badgeBg: 'bg-red-950/60 text-red-300 border-red-500/40',
      arenaBorder: 'border-[#ff0000]/40 focus-within:border-[#ff3333] focus-within:shadow-[0_0_25px_rgba(255,0,0,0.35)]',
      glow: 'shadow-[0_0_20px_rgba(255,0,0,0.25)]',
      glowEffect: 'shadow-[0_12px_36px_rgba(255,0,0,0.3)]',
      charDone: 'text-[#ff3333]',
      charCurrent: 'text-white bg-red-950/80 ring-2 ring-[#ff0000] shadow-[0_0_20px_rgba(255,0,0,0.6)]',
      cursor: 'bg-[#ff0000] shadow-[0_0_10px_#ff0000]',
    },
  },
  tiktok_neon: {
    id: 'tiktok_neon',
    name: 'Tok Glitch',
    subtitle: 'Ciano, Magenta & Batida Vertical',
    description: 'Preto absoluto com o icônico contraste anáglifo de ciano elétrico e magenta fúcsia com vibrações de ritmo.',
    price: 7,
    currency: 'tokens',
    effectType: 'tiktok_glitch',
    previewColors: {
      bg: '#010101',
      card: '#121212',
      accent: '#fe2c55',
      text: '#00f2fe',
    },
    classes: {
      appBg: 'bg-[#010101]',
      headerBg: 'bg-[#0f0f0f]/95 border-[#222222]',
      cardBg: 'bg-[#141414]',
      cardBorder: 'border-[#262626]',
      textPrimary: 'text-white',
      textSecondary: 'text-[#00f2fe]/80',
      textAccent: 'text-[#fe2c55]',
      accentBg: 'bg-[#fe2c55]/15',
      accentBorder: 'border-[#fe2c55]/40',
      badgeBg: 'bg-rose-950/60 text-rose-300 border-[#fe2c55]/40',
      arenaBorder: 'border-[#fe2c55]/50 focus-within:border-[#00f2fe] focus-within:shadow-[0_0_25px_rgba(0,242,254,0.4)]',
      glow: 'shadow-[0_0_20px_rgba(254,44,85,0.3)]',
      glowEffect: 'shadow-[0_12px_36px_rgba(0,242,254,0.35)]',
      charDone: 'text-[#00f2fe]',
      charCurrent: 'text-white bg-rose-950/80 ring-2 ring-[#fe2c55] shadow-[0_0_20px_rgba(254,44,85,0.7)]',
      cursor: 'bg-[#00f2fe] shadow-[0_0_12px_#00f2fe]',
    },
  },
  roblox_blocks: {
    id: 'roblox_blocks',
    name: 'Metaverso de Blocos',
    subtitle: 'Cubes & Mundo Quadriculado',
    description: 'Inspirado nos avatares e mundos 3D com cinza grafite, vermelho emblemático e botões geométricos.',
    price: 6,
    currency: 'tokens',
    effectType: 'roblox_grid',
    previewColors: {
      bg: '#111216',
      card: '#1b1d24',
      accent: '#e2231a',
      text: '#00a2ff',
    },
    classes: {
      appBg: 'bg-[#111216]',
      headerBg: 'bg-[#171920]/95 border-[#292c37]',
      cardBg: 'bg-[#1b1d24]',
      cardBorder: 'border-[#2e323f]',
      textPrimary: 'text-zinc-100',
      textSecondary: 'text-[#00a2ff]/80',
      textAccent: 'text-[#e2231a]',
      accentBg: 'bg-[#e2231a]/15',
      accentBorder: 'border-[#e2231a]/40',
      badgeBg: 'bg-red-950/60 text-red-300 border-red-500/40',
      arenaBorder: 'border-[#e2231a]/40 focus-within:border-[#00a2ff] focus-within:shadow-[0_0_25px_rgba(0,162,255,0.35)]',
      glow: 'shadow-[0_0_20px_rgba(226,35,26,0.25)]',
      glowEffect: 'shadow-[0_12px_36px_rgba(0,162,255,0.3)]',
      charDone: 'text-[#00a2ff]',
      charCurrent: 'text-white bg-red-950/80 ring-2 ring-[#e2231a] shadow-[0_0_20px_rgba(226,35,26,0.6)]',
      cursor: 'bg-[#00a2ff] shadow-[0_0_10px_#00a2ff]',
    },
  },
};

export interface SkinItemConfig {
  id: BytezinhoSkinId;
  name: string;
  subtitle: string;
  description: string;
  price: number;
  currency?: CosmeticCurrency;
  icon: string;
  tag: string;
  animationDescription: string;
}

export const BYTEZINHO_SKINS: Record<BytezinhoSkinId, SkinItemConfig> = {
  classic: {
    id: 'classic',
    name: 'Clássico CRT',
    subtitle: 'Padrão do Laboratório',
    description: 'O simpático monitor de tubo com fósforo verde e antena de recepção original.',
    price: 0,
    icon: '📺',
    tag: 'Padrão',
    animationDescription: 'Respiração suave e antena oscilante',
  },
  cyber: {
    id: 'cyber',
    name: 'Cibernético Neon',
    subtitle: 'Cyberpunk Visor',
    description: 'Visor de realidade aumentada com linhas neon e antena de comunicação de alta frequência.',
    price: 2,
    icon: '⚡',
    tag: 'Tecnológico',
    animationDescription: 'Jitter holográfico e sensor ótico pulsante',
  },
  retro_8bit: {
    id: 'retro_8bit',
    name: 'Retrô 8-Bits',
    subtitle: 'IBM PC 1981',
    description: 'Carcaça bege clássica com fendas de ventilação, entrada para disquete e visual nostálgico.',
    price: 3,
    icon: '💾',
    tag: 'Vintage',
    animationDescription: 'Passo escalonado 8-bit e LED ativo',
  },
  hoodie_hacker: {
    id: 'hoodie_hacker',
    name: 'Hacker com Capuz',
    subtitle: 'Modo Furtivo',
    description: 'Capuz escuro misterioso com sombras envolventes e olhar focado no código-fonte.',
    price: 3,
    icon: '🥷',
    tag: 'Furtivo',
    animationDescription: 'Respiração furtiva com sombras envolventes',
  },
  wizard: {
    id: 'wizard',
    name: 'Mago dos Códigos',
    subtitle: 'Arquimago do Algoritmo',
    description: 'Chapéu estrelado pontiagudo com aura mágica flutuante e feitiço sem bugs.',
    price: 4,
    icon: '🧙‍♂️',
    tag: 'Místico',
    animationDescription: 'Levitação mística ampla e faíscas estelares',
  },
  astronaut: {
    id: 'astronaut',
    name: 'Cosmonauta Espacial',
    subtitle: 'Gravidade Zero & Órbita',
    description: 'Traje pressurizado com capacete panorâmico, visor solar espelhado e tubo de oxigênio.',
    price: 4,
    icon: '🚀',
    tag: 'Espacial',
    animationDescription: 'Flutuação lenta em gravidade zero 360°',
  },
  ninja: {
    id: 'ninja',
    name: 'Shinobi Cibernético',
    subtitle: 'Guerreiro da Sombra',
    description: 'Bandana frontal com insígnia digital, máscara protetora ninja e reflexos rápidos.',
    price: 4,
    icon: '⚔️',
    tag: 'Ágil',
    animationDescription: 'Postura ágil e micro-dashes ultrarrápidos',
  },
  steampunk: {
    id: 'steampunk',
    name: 'Engenheiro Steampunk',
    subtitle: 'Mecânica a Vapor',
    description: 'Cartola vitoriana com óculos goggles de bronze, válvulas de escape e engrenagens.',
    price: 3,
    icon: '⚙️',
    tag: 'Vapor',
    animationDescription: 'Pulso mecânico de pistão e rotação de latão',
  },
  golden_king: {
    id: 'golden_king',
    name: 'Rei dos Bytes',
    subtitle: 'Coroa Imperial Nível 100',
    description: 'Coroa de ouro nobre com rubis lapidados, aura de realeza e brilho de prestígio imperial.',
    price: 20,
    currency: 'quantum_fragments',
    icon: '👑',
    tag: 'Quântico',
    animationDescription: 'Halo de luz dourada e postura majestosa',
  },
  diver: {
    id: 'diver',
    name: 'Mergulhador Abissal',
    subtitle: 'Exploração Submarina',
    description: 'Máscara aquática panorâmica com snorkel e bolhinhas de oxigênio ascendentes.',
    price: 3,
    icon: '🤿',
    tag: 'Aquático',
    animationDescription: 'Balanço aquático suave e bolhas subindo',
  },
  robot_mecha: {
    id: 'robot_mecha',
    name: 'Mecha de Defesa',
    subtitle: 'Blindagem Tática',
    description: 'Armadura reforçada de titânio com antenas de radar angulares e visor militar.',
    price: 4,
    icon: '🛡️',
    tag: 'Blindado',
    animationDescription: 'Varredura de radar tático e postura firme blindada',
  },
  jedi_master: {
    id: 'jedi_master',
    name: 'Mestre Jedi Bytezinho',
    subtitle: 'Cavaleiro da Força',
    description: 'Túnica de mestre estelar e sabre de luz de plasma esmeralda brilhante.',
    price: 8,
    currency: 'duel_coins',
    icon: '🧙‍♂️',
    tag: 'Jedi',
    animationDescription: 'Postura defensiva de sabre e lampejos de Força cósmica',
  },
  miner_diamond: {
    id: 'miner_diamond',
    name: 'Minerador Diamante',
    subtitle: 'Armadura Encantada',
    description: 'Elmo e armadura de diamante azul 16-bit com picareta de mineração pixelada.',
    price: 8,
    currency: 'duel_coins',
    icon: '⛏️',
    tag: 'Blocos',
    animationDescription: 'Batida rítmica de picareta e faíscas azuis de diamante',
  },
  saiyan_warrior: {
    id: 'saiyan_warrior',
    name: 'Guerreiro Saiyajin',
    subtitle: 'Poder Guerreiro Z',
    description: 'Cabelo dourado espetado Super Saiyajin com aura de ki amarela cintilante.',
    price: 10,
    currency: 'duel_coins',
    icon: '⚡',
    tag: 'Anime',
    animationDescription: 'Aura dourada ondulante e pulsação contínua de energia',
  },
  arachnid_hero: {
    id: 'arachnid_hero',
    name: 'Herói Aracnídeo',
    subtitle: 'Vigilante do Multiverso',
    description: 'Máscara com lentes brancas angulares e lançadores de teia cibernética.',
    price: 10,
    currency: 'duel_coins',
    icon: '🕸️',
    tag: 'Herói',
    animationDescription: 'Disparo ágil de teia e agilidade acrobática em alta velocidade',
  },
  // Novas Skins Míticas / Quânticas (Tier Lenda • 3ª Moeda 🌌)
  blindfolded_sorcerer: {
    id: 'blindfolded_sorcerer',
    name: 'O Feiticeiro Vendado',
    subtitle: 'Gojo / Domínio Infinito',
    description: 'Casaco gola alta preto, cabelo prateado e faixa nos olhos. No combo máximo, revela olhos azuis cósmicos radiantes.',
    price: 52,
    currency: 'quantum_fragments',
    icon: '👁️',
    tag: 'Mítico 🌌',
    animationDescription: 'Levitação cósmica com expansão de domínio e olhos azuis radiantes',
  },
  rubber_pirate: {
    id: 'rubber_pirate',
    name: 'O Pirata Emborrachado',
    subtitle: 'Luffy / Rei dos Mares',
    description: 'Colete vermelho aberto, bermuda jeans e chapéu de palha clássico. Braços se esticam alegremente a cada acerto.',
    price: 44,
    currency: 'quantum_fragments',
    icon: '👒',
    tag: 'Mítico 🌌',
    animationDescription: 'Bate palmas elásticas com vapor de Segunda Marcha',
  },
  hoodie_skeleton: {
    id: 'hoodie_skeleton',
    name: 'O Esqueleto de Moletom',
    subtitle: 'Sans / Julgamento Retrô',
    description: 'Moletom azul largo, bermuda preta, pantufas felpudas e sorriso relaxado. Órbita esquerda acende chama azul em combos.',
    price: 46,
    currency: 'quantum_fragments',
    icon: '💀',
    tag: 'Mítico 🌌',
    animationDescription: 'Chama azul na órbita esquerda e sorriso relaxado 1-bit',
  },
  urban_cyborg: {
    id: 'urban_cyborg',
    name: 'O Ciborgue Urbano',
    subtitle: 'David / Sandevistan Overdrive',
    description: 'Jaqueta amarela tática com implantes azuis luminosos na coluna. Cria clones de rastro holográfico em alta velocidade.',
    price: 48,
    currency: 'quantum_fragments',
    icon: '⚡',
    tag: 'Mítico 🌌',
    animationDescription: 'Rastros holográficos de Sandevistan e implantes neurais pulsantes',
  },
  demon_slayer: {
    id: 'demon_slayer',
    name: 'O Caçador do Quimono Xadrez',
    subtitle: 'Tanjiro / Respiração Solar',
    description: 'Casaco verde e preto quadriculado, espada de madeira nas costas e brincos retangulares tradicionais.',
    price: 45,
    currency: 'quantum_fragments',
    icon: '⚔️',
    tag: 'Mítico 🌌',
    animationDescription: 'Trilha fluida de água e dragões solares flamejantes',
  },
  electric_rodent: {
    id: 'electric_rodent',
    name: 'O Roedor Elétrico',
    subtitle: 'Pikachu / Choque do Trovão',
    description: 'Pelugem amarela, bochechas vermelhas em espiral e cauda de relâmpago que solta fagulhas a cada tecla.',
    price: 42,
    currency: 'quantum_fragments',
    icon: '⚡',
    tag: 'Mítico 🌌',
    animationDescription: 'Descarga elétrica nas bochechas e cauda de raio vibrante',
  },
  bored_hero: {
    id: 'bored_hero',
    name: 'O Herói Entediado',
    subtitle: 'Saitama / Força Incalculável',
    description: 'Cabeça raspada, olhar descontraído, luvas vermelhas e capa branca. Com 100% de acurácia, muda para traço hiper-detalhado.',
    price: 50,
    currency: 'quantum_fragments',
    icon: '🥊',
    tag: 'Mítico 🌌',
    animationDescription: 'Golpes no ar gerando ondas de choque expansivas',
  },
  needle_knight: {
    id: 'needle_knight',
    name: 'O Besouro Agulheiro',
    subtitle: 'Knight / Vazio de Hallownest',
    description: 'Máscara branca com chifres curvados e capa cinza esfarrapada empunhando uma agulha metálica de combate.',
    price: 43,
    currency: 'quantum_fragments',
    icon: '🗡️',
    tag: 'Mítico 🌌',
    animationDescription: 'Golpes rápidos de agulha e gotas de Alma luminescentes',
  },
  supersonic_hedgehog: {
    id: 'supersonic_hedgehog',
    name: 'O Ouriço Supersônico',
    subtitle: 'Sonic / Velocidade Extrema',
    description: 'Espinhos azuis para trás, tênis vermelhos reluzentes e óculos escuros. Gira em esfera de luz a partir de 80 PPM.',
    price: 41,
    currency: 'quantum_fragments',
    icon: '🦔',
    tag: 'Mítico 🌌',
    animationDescription: 'Giro supersônico com anéis dourados voando',
  },
  shadow_crusader: {
    id: 'shadow_crusader',
    name: 'O Cavaleiro das Sombras',
    subtitle: 'Batman / Detetive Mascarado',
    description: 'Armadura preta fosca com capa de asas de morcego e orelhas pontudas vigiando do topo de uma gárgula.',
    price: 46,
    currency: 'quantum_fragments',
    icon: '🦇',
    tag: 'Mítico 🌌',
    animationDescription: 'Voo noturno de asas abertas e silhuetas de morcego',
  },
};

export interface KeySoundConfig {
  id: KeySoundThemeId;
  name: string;
  subtitle: string;
  description: string;
  price: number;
  currency?: CosmeticCurrency;
  icon: string;
  type: string;
}

export const KEY_SOUNDS: Record<KeySoundThemeId, KeySoundConfig> = {
  mechanical: {
    id: 'mechanical',
    name: 'Mecânico Clicky',
    subtitle: 'Switches Azuis Clássicos',
    description: 'Batida percussiva rápida e nítida com decaimento exponencial característico.',
    price: 0,
    icon: '⌨️',
    type: 'Triangular Rápida',
  },
  retro_beep: {
    id: 'retro_beep',
    name: 'Beep 8-Bit Arcade',
    subtitle: 'Chiptune Retro',
    description: 'Beeps sonoros em onda quadrada sintetizada, lembrando os jogos de Atari e fliperama.',
    price: 2,
    icon: '👾',
    type: 'Onda Quadrada',
  },
  typewriter: {
    id: 'typewriter',
    name: 'Máquina de Escrever',
    subtitle: 'Remington Mecânica',
    description: 'Estalo encorpado e firme com onda dente de serra simulando martelos de ferro no papel.',
    price: 3,
    icon: '📜',
    type: 'Dente de Serra',
  },
  soft_click: {
    id: 'soft_click',
    name: 'Clique Suave Soft',
    subtitle: 'Silencioso & Focado',
    description: 'Clique amortecido e aveludado em onda senoidal pura, ideal para máxima concentração.',
    price: 2,
    icon: '🎧',
    type: 'Senoidal Suave',
  },
  lightsaber_clash: {
    id: 'lightsaber_clash',
    name: 'Sabre Laser & Blaster',
    subtitle: 'Guerra nas Estrelas',
    description: 'Zumbido de plasma de sabre de luz e estalos de alta frequência ao digitar.',
    price: 6,
    currency: 'duel_coins',
    icon: '⚔️',
    type: 'Plasma Laser FM',
  },
  pixel_block_jump: {
    id: 'pixel_block_jump',
    name: 'Salto & Bloco Pixel',
    subtitle: 'Arcade Platformer',
    description: 'Sons percussivos de salto e impacto de quebra de bloco estilo videogame clássico.',
    price: 6,
    currency: 'duel_coins',
    icon: '🍄',
    type: 'Arpeggio Chiptune',
  },
  ki_blast: {
    id: 'ki_blast',
    name: 'Explosão de Ki',
    subtitle: 'Poder Guerreiro Z',
    description: 'Disparo percussivo de rajada de energia cósmica com decaimento ressonante.',
    price: 6,
    currency: 'duel_coins',
    icon: '⚡',
    type: 'Pulso de Energia Sub',
  },
  // Novos Sons Míticos / Quânticos de Teclado (Tier Lenda • 3ª Moeda 🌌)
  void_pulse: {
    id: 'void_pulse',
    name: 'Pulso do Vazio Infinito',
    subtitle: 'Feiticeiro Vendado',
    description: 'Pulso dimensional gravitacional estelar com decaimento harmônico ultrarrápido.',
    price: 34,
    currency: 'quantum_fragments',
    icon: '🌌',
    type: 'Pulso Gravitacional FM',
  },
  rubber_gatling: {
    id: 'rubber_gatling',
    name: 'Metralhadora Emborrachada',
    subtitle: 'Pirata Escarlate',
    description: 'Impacto percussivo elástico e estalado em alta cadência como socos em série.',
    price: 30,
    currency: 'quantum_fragments',
    icon: '🥊',
    type: 'Percussão Elástica ADSR',
  },
  gaster_blaster: {
    id: 'gaster_blaster',
    name: 'Feixe Gaster Blaster',
    subtitle: 'Esqueleto de Moletom',
    description: 'Disparo rápido de raio laser 8-bit com ruído branco filtrado e estalo esquelético.',
    price: 32,
    currency: 'quantum_fragments',
    icon: '💀',
    type: 'Laser Chiptune 8-Bit',
  },
  sandevistan_click: {
    id: 'sandevistan_click',
    name: 'Estalo Sandevistan',
    subtitle: 'Ciborgue Urbano 2077',
    description: 'Clique mecânico hi-tech com pitch modulado descendente e eco de tempo desacelerado.',
    price: 34,
    currency: 'quantum_fragments',
    icon: '⚡',
    type: 'Hi-Tech Neural Click',
  },
  water_slash: {
    id: 'water_slash',
    name: 'Corte da Roda d\'Água',
    subtitle: 'Caçador de Quimono',
    description: 'Corte metálico limpo e ressonante combinado com respingo fluido senoidal.',
    price: 31,
    currency: 'quantum_fragments',
    icon: '🌊',
    type: 'Corte de Lâmina Acústica',
  },
  thunder_spark: {
    id: 'thunder_spark',
    name: 'Centelha do Trovão',
    subtitle: 'Roedor 100k Volts',
    description: 'Faísca elétrica de alta voltagem com estalido senoidal em micro-arpejo.',
    price: 29,
    currency: 'quantum_fragments',
    icon: '⚡',
    type: 'Arco Elétrico Senoidal',
  },
  serious_strike: {
    id: 'serious_strike',
    name: 'Impacto Sério',
    subtitle: 'Herói por Passatempo',
    description: 'Impacto sub-grave curto e seco com estalo penetrante que ecoa na arena.',
    price: 35,
    currency: 'quantum_fragments',
    icon: '👊',
    type: 'Sub-Bass Transiente',
  },
  soul_nail: {
    id: 'soul_nail',
    name: 'Agulha de Alma',
    subtitle: 'Besouro Agulheiro',
    description: 'Toque cristalino límpido e metálico com harmônicos puros de gotícula de Alma.',
    price: 30,
    currency: 'quantum_fragments',
    icon: '🗡️',
    type: 'Metal Cristalino Puro',
  },
  spin_dash: {
    id: 'spin_dash',
    name: 'Giro Supersônico & Anéis',
    subtitle: 'Ouriço Azul',
    description: 'Arpejo ultra veloz ascendente característico de aceleração e tintilar de moedas.',
    price: 29,
    currency: 'quantum_fragments',
    icon: '🦔',
    type: 'Arpeggio Supersônico',
  },
  sonar_batarang: {
    id: 'sonar_batarang',
    name: 'Sonar & Batarang Tático',
    subtitle: 'Cavaleiro das Sombras',
    description: 'Zumbido aerodinâmico afiado seguido de retorno percussivo tático de sonar.',
    price: 33,
    currency: 'quantum_fragments',
    icon: '🦇',
    type: 'Sonar Tático Militar',
  },
};
