// ─────────────────────────────────────────────────────────────
// Níveis Artesanais Pedagógicos — ScratchBot: Logic Quest
// ─────────────────────────────────────────────────────────────
import { ScratchLevelDef } from '../../../types/scratchBot';

export const PEDAGOGICAL_LEVELS: ScratchLevelDef[] = [
  {
    id: 1,
    title: 'Fase 1: Primeiros Passos',
    subtitle: 'Sequência Linear',
    description: 'Ajude Bytezinho a chegar ao portal de dados programando passos em linha reta.',
    tip: 'Use os blocos azuis "Mova 1 passo para frente" para avançar até o portal.',
    gridSize: { width: 5, height: 5 },
    startPos: { x: 1, y: 2 },
    startDir: 'RIGHT',
    targetPos: { x: 3, y: 2 },
    obstacles: [],
    maxBlocksFor3Stars: 3,
    maxBlocksFor2Stars: 4,
    baseRewardBytes: 100,
    availableBlockTypes: ['move_forward'],
  },
  {
    id: 2,
    title: 'Fase 2: Curvas e Orientação',
    subtitle: 'Mudança de Direção',
    description: 'O portal está na parte superior do circuito. Vire o robô para navegar pela curva.',
    tip: 'Lembre-se: virar não move o robô, apenas altera a direção para onde ele está olhando!',
    gridSize: { width: 5, height: 5 },
    startPos: { x: 1, y: 3 },
    startDir: 'RIGHT',
    targetPos: { x: 3, y: 1 },
    obstacles: [{ x: 3, y: 3 }, { x: 1, y: 1 }],
    maxBlocksFor3Stars: 5,
    maxBlocksFor2Stars: 7,
    baseRewardBytes: 150,
    availableBlockTypes: ['move_forward', 'turn_left', 'turn_right'],
  },
  {
    id: 3,
    title: 'Fase 3: O Poder da Repetição',
    subtitle: 'Laço Repita N Vezes',
    description: 'Um corredor longo se estende até o mainframe. Evite repetir código desnecessário!',
    tip: 'Em vez de usar vários blocos de movimento, use o bloco laranja "Repita [ 4 ] vezes".',
    gridSize: { width: 6, height: 5 },
    startPos: { x: 0, y: 2 },
    startDir: 'RIGHT',
    targetPos: { x: 5, y: 2 },
    obstacles: [{ x: 2, y: 1 }, { x: 2, y: 3 }],
    maxBlocksFor3Stars: 3, // when_flag + repeat + move_forward
    maxBlocksFor2Stars: 6,
    baseRewardBytes: 200,
    availableBlockTypes: ['move_forward', 'repeat'],
  },
  {
    id: 4,
    title: 'Fase 4: A Escadaria Lógica',
    subtitle: 'Padrões Repetitivos',
    description: 'Suba os degraus cibernéticos repetindo um padrão de movimento e curva.',
    tip: 'Identifique o padrão: Mova -> Vire Esquerda -> Mova -> Vire Direita. Coloque-o dentro de um loop!',
    gridSize: { width: 6, height: 6 },
    startPos: { x: 1, y: 4 },
    startDir: 'RIGHT',
    targetPos: { x: 4, y: 1 },
    obstacles: [
      { x: 2, y: 4 }, { x: 3, y: 4 },
      { x: 3, y: 3 }, { x: 4, y: 3 },
      { x: 4, y: 2 }
    ],
    maxBlocksFor3Stars: 6,
    maxBlocksFor2Stars: 10,
    baseRewardBytes: 250,
    availableBlockTypes: ['move_forward', 'turn_left', 'turn_right', 'repeat'],
  },
  {
    id: 5,
    title: 'Fase 5: Desvio de Firewalls',
    subtitle: 'Navegação com Obstáculos',
    description: 'Paredes de firewall bloqueiam o caminho direto. Encontre uma rota segura contornando as barreiras.',
    tip: 'Planeje sua rota antes de clicar na bandeira verde.',
    gridSize: { width: 6, height: 6 },
    startPos: { x: 0, y: 0 },
    startDir: 'RIGHT',
    targetPos: { x: 5, y: 5 },
    obstacles: [
      { x: 2, y: 0 }, { x: 2, y: 1 }, { x: 2, y: 2 },
      { x: 3, y: 3 }, { x: 3, y: 4 }, { x: 3, y: 5 }
    ],
    maxBlocksFor3Stars: 9,
    maxBlocksFor2Stars: 14,
    baseRewardBytes: 300,
    availableBlockTypes: ['move_forward', 'turn_left', 'turn_right', 'repeat'],
  },
  {
    id: 6,
    title: 'Fase 6: O Circuito Espiral',
    subtitle: 'Loops Complexos',
    description: 'Navegue pela espiral de segurança cibernética contornando a estrutura central.',
    tip: 'Loops ajudam muito em trechos retos sucessivos!',
    gridSize: { width: 7, height: 7 },
    startPos: { x: 1, y: 5 },
    startDir: 'UP',
    targetPos: { x: 3, y: 3 },
    obstacles: [
      { x: 2, y: 2 }, { x: 3, y: 2 }, { x: 4, y: 2 },
      { x: 4, y: 3 }, { x: 4, y: 4 },
      { x: 2, y: 4 }
    ],
    maxBlocksFor3Stars: 11,
    maxBlocksFor2Stars: 16,
    baseRewardBytes: 350,
    availableBlockTypes: ['move_forward', 'turn_left', 'turn_right', 'repeat'],
  },
  {
    id: 7,
    title: 'Fase 7: Coleta de Dados',
    subtitle: 'Ação e Coleta de Gemas',
    description: 'Colete todas as gemas de memória criptográfica antes de acessar o portal final!',
    tip: 'Use o bloco roxo "Coletar Gema" exatamente sobre a casa onde a gema se encontra.',
    gridSize: { width: 6, height: 6 },
    startPos: { x: 0, y: 2 },
    startDir: 'RIGHT',
    targetPos: { x: 5, y: 2 },
    obstacles: [{ x: 2, y: 1 }, { x: 2, y: 3 }],
    gems: [{ x: 2, y: 2 }, { x: 4, y: 2 }],
    maxBlocksFor3Stars: 8,
    maxBlocksFor2Stars: 12,
    baseRewardBytes: 400,
    availableBlockTypes: ['move_forward', 'turn_left', 'turn_right', 'repeat', 'collect_gem'],
  },
  {
    id: 8,
    title: 'Fase 8: Grande Desafio do Mainframe',
    subtitle: 'Mestrado em Algoritmos',
    description: 'O teste definitivo! Labirinto com barreiras e gemas preciosas. Otimize os blocos para 3 estrelas!',
    tip: 'Combine repetições inteligentes e economize passos para conquistar a pontuação perfeita.',
    gridSize: { width: 7, height: 7 },
    startPos: { x: 0, y: 6 },
    startDir: 'UP',
    targetPos: { x: 6, y: 0 },
    obstacles: [
      { x: 1, y: 5 }, { x: 1, y: 4 }, { x: 1, y: 3 },
      { x: 3, y: 6 }, { x: 3, y: 5 }, { x: 3, y: 4 }, { x: 3, y: 3 }, { x: 3, y: 2 },
      { x: 5, y: 0 }, { x: 5, y: 1 }, { x: 5, y: 2 }, { x: 5, y: 3 }
    ],
    gems: [{ x: 0, y: 2 }, { x: 2, y: 2 }, { x: 4, y: 4 }, { x: 6, y: 4 }],
    maxBlocksFor3Stars: 15,
    maxBlocksFor2Stars: 22,
    baseRewardBytes: 500,
    availableBlockTypes: ['move_forward', 'turn_left', 'turn_right', 'repeat', 'collect_gem'],
  },
];
